### ISSUE TITLE
Support JSON-RPC batching

### ISSUE THREAD

**Issue by juliangruber** [filecoin-project/lotus#11427]
### Checklist

- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated feature request to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [X] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.

By default, the [ethers v6](https://ethers.org/) JavaScript library doesn't work with lotus, because it batches JSON-RPC requests. This makes any batched request fail, previously leading me to downgrade to ethers v5, until I discovered I can also disable batching to continue using v6

### Describe the solution you'd like

JSON-RPC APIs should support batching out of the box, for compatibility with Ethereum ecosystem tooling

### Describe alternatives you've considered

Configure the client library so it doesn't batch requests

**Comment by maciejwitowski** [comment]
This is definitely important but I would bet it was fixed in https://github.com/filecoin-project/lotus/pull/10845 which updated go-jsonrpc to version which contains [batching support](https://github.com/filecoin-project/go-jsonrpc/pull/99)

**Comment by juliangruber** [comment]
I can still reproduce it:

```bash
$ curl -v 'https://api.node.glif.io' -H 'Content-Type: application/json' --data '[{"jsonrpc":"2.0","id":1,"method":"Filecoin.Version","params":[]}]'
...
< HTTP/1.1 500 Internal Server Error
```

Removing the `[]` array makes it work again. According to https://sajya.github.io/docs/batch/, this is how a batch request should look.

**Comment by maciejwitowski** [comment]
Do you maybe have a Lotus node running locally to see if there any more logs related to HTTP 500?

**Comment by juliangruber** [comment]
It works with my local instance 😲 

```
$  curl -v 'http://localhost:1234/rpc/v0' -H 'Content-Type: application/json' --data '[{"jsonrpc":"2.0","id":1,"method":"Filecoin.Version","params":[]}]'
*   Trying 127.0.0.1:1234...
* Connected to localhost (127.0.0.1) port 1234 (#0)
> POST /rpc/v0 HTTP/1.1
> Host: localhost:1234
> User-Agent: curl/8.1.2
> Accept: */*
> Content-Type: application/json
> Content-Length: 66
> 
< HTTP/1.1 200 OK
< Date: Tue, 21 Nov 2023 12:34:11 GMT
< Content-Length: 114
< Content-Type: text/plain; charset=utf-8
< 
[{"jsonrpc":"2.0","result":{"Version":"1.23.3+mainnet+git.7bb1f98ac","APIVersion":66816,"BlockDelay":30},"id":1}
* Connection #0 to host localhost left intact
]%                    
```

Maybe this is an issue with the glif node then

**Comment by maciejwitowski** [comment]
Glif nodes use `v1.23.2` which doesn't contains the batch requests PR. Glif folks are going to update their nodes to `v1.25.0` in a few days and then this will work.

**Comment by jennijuju** [comment]
thank you @maciejwitowski !  we are working on the v1.25.0 release as we speak! will close the issue for now and @juliangruber feel free to reopen this if the issue is persistent post glif node update!
