### ISSUE TITLE
Window PoSt Failed: coordinate(s) do not lie on the curve

### ISSUE THREAD

**Issue by cdcdx** [filecoin-project/lotus#3576]
** Window PoSt Failed **
coordinate(s) do not lie on the curve

** miner Log **
2020-09-05T15:26:58.969+0800	[35mDEBUG[0m	stores	stores/local.go:550	not moving {8371 35}(2); src and dest are the same
2020-09-05T15:26:58.969+0800	[35mDEBUG[0m	stores	stores/local.go:550	not moving {8371 35}(4); src and dest are the same
2020-09-05T15:26:58.969+0800	[35mDEBUG[0m	advmgr	sector-storage/sched.go:557	task done	{"workerid": 0}
2020-09-05T15:26:58.972+0800	[34mINFO[0m	sectors	storage-sealing/states_sealing.go:448	Proving sector 35
2020-09-05T15:26:58.972+0800	[33mWARN[0m	advmgr	sector-storage/manager.go:473	ReleaseUnsealed todo
2020-09-05T15:27:00.815+0800	[34mINFO[0m	rpc	go-jsonrpc@v0.1.2-0.20200822201400-474f4fdccc52/client.go:213	rpc output message buffer	{"n": 2}
2020-09-05T15:27:06.808 INFO filcrypto::proofs::api > generate_window_post: finish
2020-09-05T15:27:06.808+0800	[31mERROR[0m	storageminer	storage/wdpost_run.go:60	runPost failed: running post failed:
    github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).runPost
        /root/git-spacerace-master/lotus/storage/wdpost_run.go:409
  - coordinate(s) do not lie on the curve
    github.com/filecoin-project/filecoin-ffi.GenerateWindowPoSt
    	/root/git-spacerace-master/lotus/extern/filecoin-ffi/proofs.go:579
    github.com/filecoin-project/lotus/extern/sector-storage/ffiwrapper.(*Sealer).GenerateWindowPoSt
    	/root/git-spacerace-master/lotus/extern/sector-storage/ffiwrapper/verifier_cgo.go:41
    github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).runPost
    	/root/git-spacerace-master/lotus/storage/wdpost_run.go:407
    github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).doPost.func1
    	/root/git-spacerace-master/lotus/storage/wdpost_run.go:49
    runtime.goexit
    	/usr/lib/go-1.14/src/runtime/asm_amd64.s:1373
2020-09-05T15:27:06.808+0800	[31mERROR[0m	storageminer	storage/wdpost_run.go:29	TODO

**Version (run `lotus version`):**
lotus version 0.5.10+git.c573310c7.dirty

**Comment by jennijuju** [comment]
from another miner 
```bash
2020-09-05T23:27:51.792+0800    ^[[31mERROR^[[0m        storageminer    storage/wdpost_run.go:60        runPost failed: running post failed:
    github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).runPost
        /root/lotus/storage/wdpost_run.go:409
  - coordinate(s) do not lie on the curve
    github.com/filecoin-project/filecoin-ffi.GenerateWindowPoSt
        /root/lotus/extern/filecoin-ffi/proofs.go:579
    github.com/filecoin-project/lotus/extern/sector-storage/ffiwrapper.(*Sealer).GenerateWindowPoSt
        /root/lotus/extern/sector-storage/ffiwrapper/verifier_cgo.go:41
    github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).runPost
        /root/lotus/storage/wdpost_run.go:407
    github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).doPost.func1
        /root/lotus/storage/wdpost_run.go:49
    runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1373
2020-09-05T23:27:51.792+0800    ^[[31mERROR^[[0m        storageminer    storage/wdpost_run.go:29        TODO```

**Comment by hengic** [comment]
Before I having such issue, I restarted the miner. Is it the cause?

**Comment by rjan90** [comment]
I think this issue can be closed now, since the problem with coordinates not being on the curve has been fixed! #rengjøring

**Comment by Reiers** [comment]
**Issue solved in newer version of Lotus.**

Closing ticket. 

If you are still experiencing problems. Please visit our Discussion forum or ask for help in Slack #fil-lotus-help.

**Comment by tmzxi** [comment]
Hi, at lotus-miner version 1.14.2+mainnet+git.a03b110.dirty still have this error

error information:

2022-04-11T23:24:35.347+0800    ERROR   storageminer    storage/wdpost_run.go:681       error generating window post: not on curve

Stack backtrace:
   0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
   1: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
   2: core::iter::adapters::process_results
   3: storage_proofs_core::compound_proof::CompoundProof::circuit_proofs
   4: storage_proofs_core::compound_proof::CompoundProof::prove
   5: filecoin_proofs::api::window_post::generate_window_post
   6: filecoin_proofs_api::post::generate_window_post_inner

**Comment by Reiers** [comment]
![header](https://user-images.githubusercontent.com/63351350/163173722-a26b4ba7-c37a-4f9b-a812-cd58f5dc2bd2.png)

### **Hi @tmzxi** 

Thanks for the report ! 

I noticed that you are running a `.dirty` version of Lotus, since there been alterations to the code I cant re-open the issue.

Please upgrade to latest version [v1.15.1 ](https://github.com/filecoin-project/lotus/releases/tag/v1.15.1), and build stock Lotus. 

If the issue persist, open a new ticket, and share the logs or ask for help in our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions)

### Thank you !

_- TSE @Reiers_ 

![footer](https://user-images.githubusercontent.com/63351350/163174492-adb93b79-b203-4454-baaf-f7f5f0dbce4f.png)
