### ISSUE TITLE
Deals must be manually restarted due to data transfer failures

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#4731]
_Edit: The original issue was about protecting connections_ lest we close them when cleaning up and interrupt a transfer. They should be unprotected when the transfer completes.
_Edit: It seems that connections are already protected so the data transfer failures are being caused by a different issue._ -@dirkmc

**Comment by arajasek** [comment]
Based on some discussion with @Stebalien and @hannahhoward, this is already happening, yet @whyrusleeping reports that the majority of deals he tried needed data transfer to be restarted because the connection was closed from the remote (miner) side.

**Comment by Stebalien** [comment]
Regardless of what's happening here, we should automatically reconnect.

**Comment by dirkmc** [comment]
I spent some time today digging into this issue with @aarshkshah1992. It seems that:
- We already are [protecting the connection](https://github.com/filecoin-project/go-data-transfer/blob/master/impl/impl.go#L191) in go-data-transfer when opening push / pull channels
- We already are [attempting to reconnect](https://github.com/ipfs/go-graphsync/blob/master/messagequeue/messagequeue.go#L182) in go-graphsync when a message send fails

In order to resolve the issue I think we will need more information about why exactly the connection is being closed.

**Comment by Stebalien** [comment]
We believe the issue was yamux hitting a keepalive timeout. I believe this situation has gotten better since we fixed that bug.

**Comment by hannahhoward** [comment]
also: side note: the timeouts on reconnect in graphsync may not be long enough to overcome libp2p's dialing backoff and we may need to increase them.

**Comment by hannahhoward** [comment]
also I just realized the note about the disconnection is not resolved when we reconnect -- even if transfer resumes.

**Comment by dkkapur** [comment]
@dirkmc - fair to assume this can be closed with the fixes in markets v1.3?

**Comment by dirkmc** [comment]
Yes I'm closing, thanks Deep
