### ISSUE TITLE
sectors commit error

### ISSUE THREAD

**Issue by alingb** [filecoin-project/lotus#4968]
**Describe the problem**

After the "commitwait" state of the sector, the sector is now in the "SealPreCommit1Failed" state.How can these sectors work?

**Sectors status**
root@lotus-master:~# lotus-miner sectors status -log 125
…………
7981.	2020-11-21 13:02:26 +0800 CST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
7982.	2020-11-21 13:02:26 +0800 CST:	[event;sealing.SectorOldTicket]	{"User":{}}
7983.	2020-11-21 13:02:26 +0800 CST:	[event;sealing.SectorCommitFailed]	{"User":{}}
	sector 125 is committed but got into the GetTicket state
7984.	2020-11-21 13:02:26 +0800 CST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	ticket expired error: ticket expired: seal height: 246049, head: 254284
7985.	2020-11-21 13:03:26 +0800 CST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
7986.	2020-11-21 13:03:26 +0800 CST:	[event;sealing.SectorOldTicket]	{"User":{}}
7987.	2020-11-21 13:03:26 +0800 CST:	[event;sealing.SectorCommitFailed]	{"User":{}}
	sector 125 is committed but got into the GetTicket state
7988.	2020-11-21 13:03:26 +0800 CST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	ticket expired error: ticket expired: seal height: 246049, head: 254286
7989.	2020-11-21 13:04:26 +0800 CST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
7990.	2020-11-21 13:04:26 +0800 CST:	[event;sealing.SectorOldTicket]	{"User":{}}
7991.	2020-11-21 13:04:26 +0800 CST:	[event;sealing.SectorCommitFailed]	{"User":{}}
	sector 125 is committed but got into the GetTicket state
7992.	2020-11-21 13:04:26 +0800 CST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	ticket expired error: ticket expired: seal height: 246049, head: 254288
7993.	2020-11-21 13:05:26 +0800 CST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
7994.	2020-11-21 13:05:26 +0800 CST:	[event;sealing.SectorOldTicket]	{"User":{}}
7995.	2020-11-21 13:05:26 +0800 CST:	[event;sealing.SectorCommitFailed]	{"User":{}}
	sector 125 is committed but got into the GetTicket state
7996.	2020-11-21 13:05:26 +0800 CST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	ticket expired error: ticket expired: seal height: 246049, head: 254290
7997.	2020-11-21 13:06:26 +0800 CST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
7998.	2020-11-21 13:06:26 +0800 CST:	[event;sealing.SectorOldTicket]	{"User":{}}
7999.	2020-11-21 13:06:26 +0800 CST:	[event;sealing.SectorCommitFailed]	{"User":{}}
	sector 125 is committed but got into the GetTicket state
8000.	2020-11-23 09:52:22 +0800 CST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	ticket expired error: ticket expired: seal height: 246049, head: 259664

**Lotus miner logs**

2020-11-23T09:51:09.515+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "128"}
2020-11-23T09:51:09.516+0800	WARN	sectors	storage-sealing/fsm.go:507	sector 128 got error event sealing.SectorCommitFailed: sector 128 is committed but got into the GetTicket state
2020-11-23T09:51:09.522+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "126"}
2020-11-23T09:51:09.522+0800	WARN	sectors	storage-sealing/fsm.go:507	sector 126 got error event sealing.SectorCommitFailed: sector 126 is committed but got into the GetTicket state
2020-11-23T09:51:10.963+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "128"}
2020-11-23T09:51:10.963+0800	WARN	sectors	storage-sealing/fsm.go:507	sector 128 got error event sealing.SectorSealPreCommit1Failed: ticket expired error: ticket expired: seal height: 246138, head: 259662
2020-11-23T09:51:10.970+0800	INFO	sectors	storage-sealing/states_failed.go:26	SealPreCommit1Failed(128), waiting 59.029282445s before retrying
2020-11-23T09:51:10.991+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "126"}
2020-11-23T09:51:10.991+0800	WARN	sectors	storage-sealing/fsm.go:507	sector 126 got error event sealing.SectorSealPreCommit1Failed: ticket expired error: ticket expired: seal height: 246078, head: 259662
2020-11-23T09:51:11.000+0800	INFO	sectors	storage-sealing/states_failed.go:26	SealPreCommit1Failed(126), waiting 58.999910191s before retrying
2020-11-23T09:51:16.011+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "130"}
2020-11-23T09:51:16.050+0800	ERROR	sectors	storage-sealing/states_sealing.go:144	getting precommit info: sectorNumber is allocated, but PreCommit info wasn't found on chain
2020-11-23T09:51:16.061+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "130"}
2020-11-23T09:51:16.082+0800	ERROR	sectors	storage-sealing/states_sealing.go:97	error checking if sector is allocated: getting precommit info:
    github.com/filecoin-project/lotus/extern/storage-sealing.(*Sealing).getTicket
        /root/lotus/extern/storage-sealing/states_sealing.go:77
  - sectorNumber is allocated, but PreCommit info wasn't found on chain
2020-11-23T09:51:16.109+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "130"}
2020-11-23T09:51:16.109+0800	WARN	sectors	storage-sealing/fsm.go:507	sector 130 got error event sealing.SectorCommitFailed: sector 130 is committed but got into the GetTicket state
2020-11-23T09:51:17.392+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "130"}
2020-11-23T09:51:17.392+0800	WARN	sectors	storage-sealing/fsm.go:507	sector 130 got error event sealing.SectorSealPreCommit1Failed: ticket expired error: ticket expired: seal height: 246438, head: 259662
2020-11-23T09:51:17.410+0800	INFO	sectors	storage-sealing/states_failed.go:26	SealPreCommit1Failed(130), waiting 59.589073393s before retrying
2020-11-23T09:51:20.011+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "125"}
2020-11-23T09:51:20.011+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "127"}
2020-11-23T09:51:20.049+0800	ERROR	sectors	storage-sealing/states_sealing.go:144	getting precommit info: sectorNumber is allocated, but PreCommit info wasn't found on chain
2020-11-23T09:51:20.058+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "127"}
2020-11-23T09:51:20.066+0800	ERROR	sectors	storage-sealing/states_sealing.go:144	getting precommit info: sectorNumber is allocated, but PreCommit info wasn't found on chain
2020-11-23T09:51:20.078+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "125"}
2020-11-23T09:51:20.095+0800	ERROR	sectors	storage-sealing/states_sealing.go:97	error checking if sector is allocated: getting precommit info:
    github.com/filecoin-project/lotus/extern/storage-sealing.(*Sealing).getTicket
        /root/lotus/extern/storage-sealing/states_sealing.go:77
  - sectorNumber is allocated, but PreCommit info wasn't found on chain
2020-11-23T09:51:20.098+0800	ERROR	sectors	storage-sealing/states_sealing.go:97	error checking if sector is allocated: getting precommit info:
    github.com/filecoin-project/lotus/extern/storage-sealing.(*Sealing).getTicket
        /root/lotus/extern/storage-sealing/states_sealing.go:77
  - sectorNumber is allocated, but PreCommit info wasn't found on chain
2020-11-23T09:51:20.101+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "127"}
2020-11-23T09:51:20.101+0800	WARN	sectors	storage-sealing/fsm.go:507	sector 127 got error event sealing.SectorCommitFailed: sector 127 is committed but got into the GetTicket state
2020-11-23T09:51:20.110+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "125"}
2020-11-23T09:51:20.110+0800	WARN	sectors	storage-sealing/fsm.go:507	sector 125 got error event sealing.SectorCommitFailed: sector 125 is committed but got into the GetTicket state
2020-11-23T09:51:21.515+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "125"}
2020-11-23T09:51:21.515+0800	WARN	sectors	storage-sealing/fsm.go:507	sector 125 got error event sealing.SectorSealPreCommit1Failed: ticket expired error: ticket expired: seal height: 246049, head: 259662
2020-11-23T09:51:21.537+0800	INFO	sectors	storage-sealing/states_failed.go:26	SealPreCommit1Failed(125), waiting 59.462024498s before retrying
2020-11-23T09:51:21.559+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "127"}
2020-11-23T09:51:21.560+0800	WARN	sectors	storage-sealing/fsm.go:507	sector 127 got error event sealing.SectorSealPreCommit1Failed: ticket expired error: ticket expired: seal height: 246108, head: 259662
2020-11-23T09:51:21.569+0800	INFO	sectors	storage-sealing/states_failed.go:26	SealPreCommit1Failed(127), waiting 59.43033195s before retrying

root@lotus-master:~# lotus-miner storage find 125
In ad9287a3-2e5e-4edc-8c34-0ef9c257d8a8 (Unsealed)
	Sealing: true; Storage: false
	Remote
	URL: http://192.168.1.14:1129/remote/unsealed/s-t057466-125
In efe7552f-755a-4ffe-afb9-b87115bb4697 (Sealed, Cache)
	Sealing: true; Storage: false
	Local (/nvme1/LOTUS_WORKER_PATH/)
	URL: http://192.168.1.12:1124/remote/sealed/s-t057466-125
	URL: http://192.168.1.12:2345/remote/sealed/s-t057466-125

**Lotus miner diagnostic info**

Please collect the following diagnostic information, and share a link here

* lotus-miner diagnostic info `lotus-miner info all > allinfo`

** Code modifications **

N/A

**Version**

root@lotus-master:~# lotus version
Daemon:  1.2.0+git.648f02cbd.dirty+api1.0.0
Local: lotus version 1.2.0+git.648f02cbd.dirty

**Comment by jennijuju** [comment]
please try https://github.com/filecoin-project/lotus/pull/4876, it should fix this

**Comment by alingb** [comment]
@jennijuju after I upgrade the new version and restart miner, there is a new error:
root@lotus-master:~# lotus-miner sectors list
……
125  CommitFailed  NO       NO      n/a                           CC
126  CommitFailed  NO       NO      n/a                           CC
127  CommitFailed  NO       NO      n/a                           CC
128  CommitFailed  NO       NO      n/a                           CC
129  Proving       YES      YES     1800878 (in 1 year 23 weeks)  CC
130  CommitFailed  NO       NO      n/a                           CC
……


root@lotus-master:~# lotus-miner sectors status -log 126
…………
7996.	2020-11-21 13:22:26 +0800 CST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	ticket expired error: ticket expired: seal height: 246078, head: 254324
7997.	2020-11-21 13:23:26 +0800 CST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
7998.	2020-11-21 13:23:26 +0800 CST:	[event;sealing.SectorOldTicket]	{"User":{}}
7999.	2020-11-21 13:23:26 +0800 CST:	[event;sealing.SectorCommitFailed]	{"User":{}}
	sector 126 is committed but got into the GetTicket state
8000.	2020-11-26 16:50:39 +0800 CST:	[event;sealing.SectorCommitFailed]	{"User":{}}
	failed to wait for porep inclusion: failed to load message: blockstore: block not found


miner.log
2020-11-26T16:47:39.060+0800	INFO	sectors	storage-sealing/states_failed.go:26	CommitFailed(130), waiting 59.939616602s before retrying
2020-11-26T16:47:39.064+0800	INFO	sectors	storage-sealing/states_failed.go:26	CommitFailed(125), waiting 59.935641873s before retrying
2020-11-26T16:47:39.075+0800	INFO	sectors	storage-sealing/states_failed.go:26	CommitFailed(126), waiting 59.924341535s before retrying
2020-11-26T16:47:39.079+0800	INFO	sectors	storage-sealing/states_failed.go:26	CommitFailed(128), waiting 59.920837891s before retrying
2020-11-26T16:48:39.011+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "128"}
2020-11-26T16:48:39.011+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "126"}
2020-11-26T16:48:39.012+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "130"}
2020-11-26T16:48:39.014+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "125"}
2020-11-26T16:48:39.014+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "127"}
2020-11-26T16:48:39.028+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "128"}
2020-11-26T16:48:39.028+0800	WARN	sectors	storage-sealing/fsm.go:507	sector 128 got error event sealing.SectorCommitFailed: failed to wait for porep inclusion: failed to load message: blockstore: block not found
2020-11-26T16:48:39.045+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "126"}
2020-11-26T16:48:39.045+0800	WARN	sectors	storage-sealing/fsm.go:507	sector 126 got error event sealing.SectorCommitFailed: failed to wait for porep inclusion: failed to load message: blockstore: block not found
2020-11-26T16:48:39.048+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "130"}
2020-11-26T16:48:39.050+0800	WARN	sectors	storage-sealing/fsm.go:507	sector 130 got error event sealing.SectorCommitFailed: failed to wait for porep inclusion: failed to load message: blockstore: block not found
2020-11-26T16:48:39.055+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "125"}
2020-11-26T16:48:39.055+0800	WARN	sectors	storage-sealing/fsm.go:507	sector 125 got error event sealing.SectorCommitFailed: failed to wait for porep inclusion: failed to load message: blockstore: block not found
2020-11-26T16:48:39.058+0800	INFO	sectors	storage-sealing/states_failed.go:26	CommitFailed(128), waiting 59.941681794s before retrying
2020-11-26T16:48:39.058+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "127"}
2020-11-26T16:48:39.058+0800	WARN	sectors	storage-sealing/fsm.go:507	sector 127 got error event sealing.SectorCommitFailed: failed to wait for porep inclusion: failed to load message: blockstore: block not found
2020-11-26T16:48:39.065+0800	INFO	sectors	storage-sealing/states_failed.go:26	CommitFailed(130), waiting 59.934117914s before retrying
2020-11-26T16:48:39.081+0800	INFO	sectors	storage-sealing/states_failed.go:26	CommitFailed(126), waiting 59.918984756s before retrying
2020-11-26T16:48:39.089+0800	INFO	sectors	storage-sealing/states_failed.go:26	CommitFailed(125), waiting 59.91027114s before retrying
2020-11-26T16:48:39.090+0800	INFO	sectors	storage-sealing/states_failed.go:26	CommitFailed(127), waiting 59.909691001s before retrying
2020-11-26T16:49:39.013+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "128"}
2020-11-26T16:49:39.013+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "125"}
2020-11-26T16:49:39.014+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "127"}
2020-11-26T16:49:39.015+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "130"}
2020-11-26T16:49:39.016+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "126"}
2020-11-26T16:49:39.029+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "125"}
2020-11-26T16:49:39.029+0800	WARN	sectors	storage-sealing/fsm.go:507	sector 125 got error event sealing.SectorCommitFailed: failed to wait for porep inclusion: failed to load message: blockstore: block not found
2020-11-26T16:49:39.032+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "128"}
2020-11-26T16:49:39.032+0800	WARN	sectors	storage-sealing/fsm.go:507	sector 128 got error event sealing.SectorCommitFailed: failed to wait for porep inclusion: failed to load message: blockstore: block not found
2020-11-26T16:49:39.037+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "127"}
2020-11-26T16:49:39.037+0800	WARN	sectors	storage-sealing/fsm.go:507	sector 127 got error event sealing.SectorCommitFailed: failed to wait for porep inclusion: failed to load message: blockstore: block not found
2020-11-26T16:49:39.040+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "130"}
2020-11-26T16:49:39.041+0800	WARN	sectors	storage-sealing/fsm.go:507	sector 130 got error event sealing.SectorCommitFailed: failed to wait for porep inclusion: failed to load message: blockstore: block not found
2020-11-26T16:49:39.048+0800	INFO	sectors	storage-sealing/states_failed.go:26	CommitFailed(125), waiting 59.95127666s before retrying
2020-11-26T16:49:39.051+0800	INFO	sectors	storage-sealing/states_failed.go:26	CommitFailed(128), waiting 59.948140551s before retrying
2020-11-26T16:49:39.053+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "126"}
2020-11-26T16:49:39.053+0800	WARN	sectors	storage-sealing/fsm.go:507	sector 126 got error event sealing.SectorCommitFailed: failed to wait for porep inclusion: failed to load message: blockstore: block not found
2020-11-26T16:49:39.060+0800	INFO	sectors	storage-sealing/states_failed.go:26	CommitFailed(127), waiting 59.939612533s before retrying
2020-11-26T16:49:39.065+0800	INFO	sectors	storage-sealing/states_failed.go:26	CommitFailed(130), waiting 59.934842358s before retrying
2020-11-26T16:49:39.075+0800	INFO	sectors	storage-sealing/states_failed.go:26	CommitFailed(126), waiting 59.924127745s before retrying
2020-11-26T16:50:39.014+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "126"}
2020-11-26T16:50:39.014+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "127"}
2020-11-26T16:50:39.014+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "125"}
2020-11-26T16:50:39.015+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "130"}
2020-11-26T16:50:39.015+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "128"}
2020-11-26T16:50:39.028+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "126"}
2020-11-26T16:50:39.028+0800	WARN	sectors	storage-sealing/fsm.go:507	sector 126 got error event sealing.SectorCommitFailed: failed to wait for porep inclusion: failed to load message: blockstore: block not found
2020-11-26T16:50:39.033+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "127"}
2020-11-26T16:50:39.037+0800	WARN	sectors	storage-sealing/fsm.go:507	sector 127 got error event sealing.SectorCommitFailed: failed to wait for porep inclusion: failed to load message: blockstore: block not found
2020-11-26T16:50:39.052+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "125"}
2020-11-26T16:50:39.052+0800	WARN	sectors	storage-sealing/fsm.go:507	sector 125 got error event sealing.SectorCommitFailed: failed to wait for porep inclusion: failed to load message: blockstore: block not found
2020-11-26T16:50:39.055+0800	INFO	sectors	storage-sealing/states_failed.go:26	CommitFailed(126), waiting 59.94427307s before retrying
2020-11-26T16:50:39.060+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "130"}
2020-11-26T16:50:39.061+0800	WARN	sectors	storage-sealing/fsm.go:507	sector 130 got error event sealing.SectorCommitFailed: failed to wait for porep inclusion: failed to load message: blockstore: block not found
2020-11-26T16:50:39.060+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "128"}
2020-11-26T16:50:39.061+0800	WARN	sectors	storage-sealing/fsm.go:507	sector 128 got error event sealing.SectorCommitFailed: failed to wait for porep inclusion: failed to load message: blockstore: block not found
2020-11-26T16:50:39.069+0800	INFO	sectors	storage-sealing/states_failed.go:26	CommitFailed(125), waiting 59.930465003s before retrying
2020-11-26T16:50:39.072+0800	INFO	sectors	storage-sealing/states_failed.go:26	CommitFailed(127), waiting 59.927071668s before retrying
2020-11-26T16:50:39.080+0800	INFO	sectors	storage-sealing/states_failed.go:26	CommitFailed(130), waiting 59.919337466s before retrying
2020-11-26T16:50:39.081+0800	INFO	sectors	storage-sealing/states_failed.go:26	CommitFailed(128), waiting 59.918666379s before retrying
2020-11-26T16:51:39.012+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "127"}
2020-11-26T16:51:39.012+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "126"}
2020-11-26T16:51:39.012+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "130"}
2020-11-26T16:51:39.014+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "128"}
2020-11-26T16:51:39.014+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "125"}
2020-11-26T16:51:39.029+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "130"}
2020-11-26T16:51:39.029+0800	WARN	sectors	storage-sealing/fsm.go:507	sector 130 got error event sealing.SectorCommitFailed: failed to wait for porep inclusion: failed to load message: blockstore: block not found
2020-11-26T16:51:39.036+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "127"}
2020-11-26T16:51:39.036+0800	WARN	sectors	storage-sealing/fsm.go:507	sector 127 got error event sealing.SectorCommitFailed: failed to wait for porep inclusion: failed to load message: blockstore: block not found
2020-11-26T16:51:39.036+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "126"}
2020-11-26T16:51:39.036+0800	WARN	sectors	storage-sealing/fsm.go:507	sector 126 got error event sealing.SectorCommitFailed: failed to wait for porep inclusion: failed to load message: blockstore: block not found
2020-11-26T16:51:39.043+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "128"}
2020-11-26T16:51:39.043+0800	WARN	sectors	storage-sealing/fsm.go:507	sector 128 got error event sealing.SectorCommitFailed: failed to wait for porep inclusion: failed to load message: blockstore: block not found
2020-11-26T16:51:39.048+0800	INFO	sectors	storage-sealing/states_failed.go:26	CommitFailed(130), waiting 59.951035462s before retrying
2020-11-26T16:51:39.054+0800	INFO	sectors	storage-sealing/states_failed.go:26	CommitFailed(127), waiting 59.945811206s before retrying
2020-11-26T16:51:39.056+0800	WARN	sectors	storage-sealing/fsm.go:188	truncating sector log	{"sector": "125"}
2020-11-26T16:51:39.063+0800	WARN	sectors	storage-sealing/fsm.go:507	sector 125 got error event sealing.SectorCommitFailed: failed to wait for porep inclusion: failed to load message: blockstore: block not found
2020-11-26T16:51:39.071+0800	INFO	sectors	storage-sealing/states_failed.go:26	CommitFailed(126), waiting 59.928818696s before retrying
2020-11-26T16:51:39.074+0800	INFO	sectors	storage-sealing/states_failed.go:26	CommitFailed(128), waiting 59.925818592s before retrying
2020-11-26T16:51:39.076+0800	INFO	sectors	storage-sealing/states_failed.go:26	CommitFailed(125), waiting 59.923538276s before retrying


root@lotus-master:~# lotus --version
lotus version 1.2.1+git.d15d9b0fb.dirty

**Comment by utgarda** [comment]
Still getting that with v1.8.0 - these messages are going in a loop:
```
{"level":"info","ts":"2021-04-30T05:20:16.007+0300","logger":"sectors","caller":"storage-sealing/states_failed.go:26","msg":"CommitFailed(17), waiting 59.992959089s before retrying"}
{"level":"info","ts":"2021-04-30T05:20:16.013+0300","logger":"sectors","caller":"storage-sealing/states_failed.go:26","msg":"PreCommitFailed(22), waiting 59.986497249s before retrying"}
{"level":"info","ts":"2021-04-30T05:20:16.014+0300","logger":"sectors","caller":"storage-sealing/states_failed.go:26","msg":"PreCommitFailed(20), waiting 59.985350455s before retrying"}
{"level":"info","ts":"2021-04-30T05:20:16.015+0300","logger":"sectors","caller":"storage-sealing/states_failed.go:26","msg":"CommitFailed(16), waiting 59.9841843s before retrying"}
{"level":"info","ts":"2021-04-30T05:20:16.015+0300","logger":"sectors","caller":"storage-sealing/states_failed.go:26","msg":"PreCommitFailed(21), waiting 59.98417007s before retrying"}
{"level":"warn","ts":"2021-04-30T05:21:16.004+0300","logger":"sectors","caller":"storage-sealing/fsm.go:509","msg":"sector 22 got error event sealing.SectorChainPreCommitFailed: failed to load message: blockstore: block not found"}
{"level":"warn","ts":"2021-04-30T05:21:16.004+0300","logger":"sectors","caller":"storage-sealing/fsm.go:509","msg":"sector 21 got error event sealing.SectorChainPreCommitFailed: failed to load message: blockstore: block not found"}
{"level":"warn","ts":"2021-04-30T05:21:16.006+0300","logger":"sectors","caller":"storage-sealing/fsm.go:509","msg":"sector 17 got error event sealing.SectorCommitFailed: failed to wait for porep inclusion: failed to load message: blockstore: block not found"}
{"level":"warn","ts":"2021-04-30T05:21:16.006+0300","logger":"sectors","caller":"storage-sealing/fsm.go:509","msg":"sector 20 got error event sealing.SectorChainPreCommitFailed: failed to load message: blockstore: block not found"}
{"level":"warn","ts":"2021-04-30T05:21:16.006+0300","logger":"sectors","caller":"storage-sealing/fsm.go:509","msg":"sector 16 got error event sealing.SectorCommitFailed: failed to wait for porep inclusion: failed to load message: blockstore: block not found"}
```

**Comment by utgarda** [comment]
@jennijuju what kind of helpful detail can I add?
