### ISSUE TITLE
macOS 12.0 make failed

### ISSUE THREAD

**Issue by jitash** [filecoin-project/lotus#7597]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [X] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus version 1.13.1-rc1+mainnet+git.6fbaba132.dirty
```

### Describe the Bug

I can not make lotus from macOS 12.0 (with M1 chip).
There seems to be a problem with this library.

# github.com/zondax/hid
In file included from ../../../../go/pkg/mod/github.com/zondax/hid@v0.9.0/hid_enabled.go:38:
../../../../go/pkg/mod/github.com/zondax/hid@v0.9.0/hidapi/mac/hid.c:693:34: warning: 'kIOMasterPortDefault' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]

### Logging Information

```text
rm -rf  build/.filecoin-install build/.update-modules  lotus lotus-miner lotus-worker lotus-shed lotus-gateway lotus-seed lotus-pond lotus-fountain lotus-bench lotus-stats lotus-pcr lotus-health lotus-wallet lotus-keygen testground tvx lotus-sim
/Library/Developer/CommandLineTools/usr/bin/make -C extern/filecoin-ffi/ clean
go clean -cache -testcache .
rm -rf filcrypto.h filcrypto.pc libfilcrypto.a .install-filcrypto
rm -f ./runner
cd rust && cargo clean && cd ..
git submodule update --init --recursive
Submodule path 'extern/filecoin-ffi': checked out '7912389334e347bbb2eac0520c836830875c39de'
touch build/.update-modules
/Library/Developer/CommandLineTools/usr/bin/make -C extern/filecoin-ffi/ .install-filcrypto
go clean -cache -testcache .
./install-filcrypto
+ auth_header=()
+ '[' -n '' ']'
++ dirname ./install-filcrypto
+ cd .
+ rust_sources_dir=rust
++ jq -r '.[].check_cpu_for_feature | select(. != null)'
+ cpu_features_required_for_optimized_release='adx
sha_ni
sha2
sse2
avx2
avx
sse4_2
sse4_1'
+ main
++ get_release_flags
++ local __features=
++ [[ ! -f /proc/cpuinfo ]]
++ echo '[get_release_flags] no /proc/cpuinfo file; falling back to Darwin feature detection'
[get_release_flags] no /proc/cpuinfo file; falling back to Darwin feature detection
+++ sysctl -a
+++ grep machdep.cpu
+++ tr '[:upper:]' '[:lower:]'
+++ grep features
++ __features=
+++ uname -s
++ '[' Darwin = Darwin ']'
+++ uname -m
++ '[' arm64 = x86_64 ']'
++ feature_map=("adx:+adx" "sha_ni:+sha" "sha2:+sha2" "sse2:+sse2" "avx2:+avx2" "avx:+avx" "sse4_2:+sse4.2" "sse4_1:+sse4.1")
++ target_features=
++ for x in '${cpu_features_required_for_optimized_release[@]}'
+++ echo ''
+++ grep -c adx
++ current_feature=0
++ '[' 1 = 0 ']'
++ for x in '${cpu_features_required_for_optimized_release[@]}'
+++ echo ''
+++ grep -c sha_ni
++ current_feature=0
++ '[' 1 = 0 ']'
++ for x in '${cpu_features_required_for_optimized_release[@]}'
+++ echo ''
+++ grep -c sha2
++ current_feature=0
++ '[' 1 = 0 ']'
++ for x in '${cpu_features_required_for_optimized_release[@]}'
+++ echo ''
+++ grep -c sse2
++ current_feature=0
++ '[' 1 = 0 ']'
++ for x in '${cpu_features_required_for_optimized_release[@]}'
+++ echo ''
+++ grep -c avx2
++ current_feature=0
++ '[' 1 = 0 ']'
++ for x in '${cpu_features_required_for_optimized_release[@]}'
+++ echo ''
+++ grep -c avx
++ current_feature=0
++ '[' 1 = 0 ']'
++ for x in '${cpu_features_required_for_optimized_release[@]}'
+++ echo ''
+++ grep -c sse4_2
++ current_feature=0
++ '[' 1 = 0 ']'
++ for x in '${cpu_features_required_for_optimized_release[@]}'
+++ echo ''
+++ grep -c sse4_1
++ current_feature=0
++ '[' 1 = 0 ']'
++ echo ''
+ local __release_flags=
+ '[' 1 '!=' 1 ']'
+ echo '[install-filcrypto/main] building libfilcrypto from local sources (dir = rust)'
[install-filcrypto/main] building libfilcrypto from local sources (dir = rust)
+ build_from_source filcrypto rust ''
+ local __library_name=filcrypto
+ local __rust_sources_path=rust
+ local __release_flags=
++ git rev-parse HEAD
+ local __repo_sha1=7912389334e347bbb2eac0520c836830875c39de
+ local __repo_sha1_truncated=7912389334e347bb
+ echo 'building from source @ 7912389334e347bb'
building from source @ 7912389334e347bb
++ command -v cargo
+ '[' -x /Users/jitash/.cargo/bin/cargo ']'
++ command -v rustup
+ '[' -x /Users/jitash/.cargo/bin/rustup ']'
+ pushd rust
~/Data/Projects/GoProjects/lotus_official/extern/filecoin-ffi/rust ~/Data/Projects/GoProjects/lotus_official/extern/filecoin-ffi
+ cargo --version
info: syncing channel updates for 'nightly-2021-07-29-aarch64-apple-darwin'
info: latest update on 2021-07-29, rust version 1.56.0-nightly (b70888601 2021-07-28)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: downloading component 'rustfmt'
info: installing component 'cargo'
info: installing component 'clippy'
info: installing component 'rust-std'
info: installing component 'rustc'
info: installing component 'rustfmt'
cargo 1.55.0-nightly (d21c22870 2021-07-26)
+ additional_flags=
++ uname -s
+ '[' Darwin = Darwin ']'
++ uname -m
+ '[' arm64 = x86_64 ']'
+ build=build
+ gpu_flags=,opencl
+ '[' '' == 1 ']'
+ '[' '' == 0 ']'
+ use_multicore_sdr=multicore-sdr
+ '[' '' == 0 ']'
+ '[' '' == 1 ']'
+ additional_flags=' --no-default-features --features multicore-sdr,opencl'
+ echo 'Using additional build flags:  --no-default-features --features multicore-sdr,opencl'
Using additional build flags:  --no-default-features --features multicore-sdr,opencl
+ '[' -n '' ']'
++ cat rust-toolchain
+ ./scripts/build-release.sh filcrypto nightly-2021-07-29 build ' --no-default-features --features multicore-sdr,opencl'
+ main filcrypto nightly-2021-07-29 build ' --no-default-features --features multicore-sdr,opencl'
+ [[ -z filcrypto ]]
+ [[ -z nightly-2021-07-29 ]]
+ [[ -z build ]]
++ mktemp
+ __build_output_log_tmp=/var/folders/tt/tkhky6ws4yj097791hdbg0mr0000gn/T/tmp.KDtPwTgx
+ trap '{ rm -f $__build_output_log_tmp; }' EXIT
+ local '__rust_flags=--print native-static-libs '
+ RUSTFLAGS='--print native-static-libs '
+ tee /var/folders/tt/tkhky6ws4yj097791hdbg0mr0000gn/T/tmp.KDtPwTgx
+ cargo +nightly-2021-07-29 build --release --no-default-features --features multicore-sdr,opencl
 Downloading crates ...
  Downloaded cc v1.0.71
  Downloaded ppv-lite86 v0.2.15
  Downloaded storage-proofs-post v10.1.0
  Downloaded proc-macro2 v1.0.30
  Downloaded storage-proofs-porep v10.1.0
  Downloaded synstructure v0.12.6
  Downloaded syn v1.0.80
  Downloaded quote v1.0.10
  Downloaded thiserror v1.0.30
  Downloaded sha2raw v5.1.0
  Downloaded filecoin-proofs-api v10.1.0
  Downloaded pkg-config v0.3.22
  Downloaded fr32 v3.1.0
  Downloaded storage-proofs-core v10.1.0
  Downloaded thiserror-impl v1.0.30
  Downloaded bellperson v0.18.0
  Downloaded libc v0.2.105
  Downloaded bls-signatures v0.11.1
  Downloaded byte-slice-cast v1.2.0
  Downloaded filecoin-proofs v10.1.0
  Downloaded filecoin-hashers v5.1.0
  Downloaded blstrs v0.4.1
  Downloaded blst v0.3.6
  Downloaded neptune v5.1.0
   Compiling libc v0.2.105
   Compiling proc-macro2 v1.0.30
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.80
   Compiling cfg-if v1.0.0
   Compiling autocfg v1.0.1
   Compiling typenum v1.14.0
   Compiling version_check v0.9.3
   Compiling serde v1.0.130
   Compiling serde_derive v1.0.130
   Compiling cc v1.0.71
   Compiling radium v0.6.2
   Compiling lazy_static v1.4.0
   Compiling ppv-lite86 v0.2.15
   Compiling glob v0.3.0
   Compiling log v0.4.14
   Compiling scopeguard v1.1.0
   Compiling crossbeam-utils v0.8.5
   Compiling tap v1.0.1
   Compiling funty v1.2.0
   Compiling byteorder v1.4.3
   Compiling ryu v1.0.5
   Compiling subtle v2.4.1
   Compiling execute-command-tokens v0.1.4
   Compiling crossbeam-epoch v0.9.5
   Compiling either v1.6.1
   Compiling ec-gpu v0.1.0
   Compiling byte-slice-cast v1.2.0
   Compiling arrayvec v0.5.2
   Compiling rayon-core v1.9.1
   Compiling cl-sys v0.4.2
   Compiling opaque-debug v0.3.0
   Compiling memchr v2.4.1
   Compiling getrandom v0.1.16
   Compiling byte-tools v0.3.1
   Compiling hex v0.4.3
   Compiling serde_json v1.0.68
   Compiling arrayref v0.3.6
   Compiling fake-simd v0.1.2
   Compiling constant_time_eq v0.1.5
   Compiling opaque-debug v0.2.3
   Compiling cfg-if v0.1.10
   Compiling anyhow v1.0.44
   Compiling lexical-core v0.7.6
   Compiling remove_dir_all v0.5.3
   Compiling rustc-serialize v0.3.24
   Compiling ucd-trie v0.1.3
   Compiling static_assertions v1.1.0
   Compiling byteorder v0.5.3
   Compiling bitflags v1.3.2
   Compiling crossbeam-queue v0.3.2
   Compiling pkg-config v0.3.22
   Compiling itoa v0.4.8
   Compiling regex-syntax v0.6.25
   Compiling block-padding v0.2.1
   Compiling proc-macro2 v0.4.30
   Compiling unicode-width v0.1.9
   Compiling unicode-xid v0.1.0
   Compiling yansi v0.5.0
   Compiling ansi_term v0.11.0
   Compiling syn v0.15.44
   Compiling difference v2.0.0
   Compiling vec_map v0.8.2
   Compiling strsim v0.8.0
   Compiling bitflags v0.4.0
   Compiling cbindgen v0.14.0
   Compiling radium v0.3.0
   Compiling fff v0.3.1
   Compiling once_cell v1.8.0
   Compiling generic-array v0.14.4
   Compiling nom v5.1.2
   Compiling memoffset v0.6.4
   Compiling num-traits v0.2.14
   Compiling num-integer v0.1.44
   Compiling rayon v1.5.1
   Compiling num-iter v0.1.42
   Compiling num-bigint v0.2.6
   Compiling lock_api v0.4.5
   Compiling wyz v0.4.0
   Compiling itertools v0.10.1
   Compiling itertools v0.8.2
   Compiling itertools v0.9.0
   Compiling ec-gpu-gen v0.1.1
   Compiling block-padding v0.1.5
   Compiling sha2-asm v0.6.2
   Compiling blst v0.3.6
   Compiling blake2s_simd v0.5.11
   Compiling blake2b_simd v0.5.11
   Compiling pest v2.1.3
   Compiling textwrap v0.11.0
   Compiling hwloc v0.3.0
   Compiling pretty_assertions v0.6.1
   Compiling bitvec v0.17.4
   Compiling spin v0.9.2
   Compiling semver-parser v0.10.2
   Compiling getrandom v0.2.3
   Compiling num_cpus v1.13.0
   Compiling rand v0.4.6
   Compiling dirs-sys v0.3.6
   Compiling cpufeatures v0.2.1
   Compiling memmap v0.7.0
   Compiling fs2 v0.4.3
   Compiling positioned-io v0.2.2
   Compiling time v0.1.43
   Compiling errno v0.1.8
   Compiling atty v0.2.14
   Compiling mapr v0.8.0
   Compiling fdlimit v0.2.1
   Compiling filepath v0.1.1
   Compiling flume v0.10.9
   Compiling quote v1.0.10
   Compiling bitvec v0.22.3
   Compiling generic-array v0.12.4
   Compiling crossbeam-channel v0.5.1
   Compiling aho-corasick v0.7.18
   Compiling semver v0.11.0
   Compiling threadpool v1.8.1
   Compiling rand_core v0.6.3
   Compiling cl3 v0.4.4
   Compiling dirs v2.0.2
   Compiling rand_core v0.5.1
   Compiling tempdir v0.3.7
   Compiling clap v2.33.3
   Compiling yastl v0.1.2
   Compiling quote v0.6.13
   Compiling digest v0.9.0
   Compiling block-buffer v0.9.0
   Compiling digest v0.8.1
   Compiling block-buffer v0.7.3
   Compiling cipher v0.2.5
   Compiling regex v1.5.4
   Compiling num-complex v0.1.43
   Compiling rand_chacha v0.3.1
   Compiling rand_xorshift v0.3.0
   Compiling opencl3 v0.4.1
   Compiling ff v0.11.0
   Compiling rand_chacha v0.2.2
   Compiling sha2 v0.9.8
   Compiling sha2 v0.8.2
   Compiling crossbeam-deque v0.8.1
   Compiling sha2raw v5.1.0
   Compiling aes-soft v0.6.4
   Compiling block-modes v0.7.0
   Compiling num-bigint v0.1.44
   Compiling chrono v0.4.19
   Compiling rand v0.8.4
   Compiling rand v0.7.3
   Compiling synstructure v0.12.6
   Compiling crossbeam v0.8.1
   Compiling aes v0.6.0
   Compiling num-rational v0.1.42
   Compiling flexi_logger v0.14.8
   Compiling drop_struct_macro_derive v0.5.0
   Compiling group v0.11.0
   Compiling tempfile v3.2.0
   Compiling execute-command-macro-impl v0.1.6
   Compiling thiserror-impl v1.0.30
   Compiling zeroize_derive v1.2.0
   Compiling num v0.1.42
   Compiling fil_logger v0.1.3
   Compiling pairing v0.21.0
   Compiling ffi-toolkit v0.5.0
   Compiling execute-command-macro v0.1.6
   Compiling zeroize v1.4.2
   Compiling thiserror v1.0.30
   Compiling execute v0.2.9
   Compiling rust-gpu-tools v0.5.0
   Compiling blstrs v0.4.1
   Compiling toml v0.5.8
   Compiling bincode v1.3.3
   Compiling merkletree v0.21.0
   Compiling bls-signatures v0.11.1
   Compiling config v0.10.1
   Compiling bellperson v0.18.0
   Compiling neptune v5.1.0
   Compiling fr32 v3.1.0
   Compiling filecoin-hashers v5.1.0
   Compiling filcrypto v0.7.5 (/Users/jitash/Data/Projects/GoProjects/lotus_official/extern/filecoin-ffi/rust)
   Compiling storage-proofs-core v10.1.0
   Compiling storage-proofs-porep v10.1.0
   Compiling storage-proofs-post v10.1.0
   Compiling filecoin-proofs v10.1.0
   Compiling filecoin-proofs-api v10.1.0
note: Link against the following native artifacts when linking against this static library. The order and any duplication can be significant on some platforms.

note: native-static-libs: -lhwloc -framework OpenCL -framework OpenCL -framework OpenCL -framework OpenCL -framework OpenCL -framework OpenCL -framework OpenCL -framework OpenCL -framework OpenCL -framework OpenCL -framework OpenCL -liconv -lSystem -lresolv -lc -lm -liconv

    Finished release [optimized] target(s) in 1m 45s
++ cat /var/folders/tt/tkhky6ws4yj097791hdbg0mr0000gn/T/tmp.KDtPwTgx
++ head -n 1
++ cut -d : -f 3
++ grep native-static-libs:
+ local '__linker_flags= -lhwloc -framework OpenCL -framework OpenCL -framework OpenCL -framework OpenCL -framework OpenCL -framework OpenCL -framework OpenCL -framework OpenCL -framework OpenCL -framework OpenCL -framework OpenCL -liconv -lSystem -lresolv -lc -lm -liconv'
+ echo 'Linker Flags:  -lhwloc -framework OpenCL -framework OpenCL -framework OpenCL -framework OpenCL -framework OpenCL -framework OpenCL -framework OpenCL -framework OpenCL -framework OpenCL -framework OpenCL -framework OpenCL -liconv -lSystem -lresolv -lc -lm -liconv'
Linker Flags:  -lhwloc -framework OpenCL -framework OpenCL -framework OpenCL -framework OpenCL -framework OpenCL -framework OpenCL -framework OpenCL -framework OpenCL -framework OpenCL -framework OpenCL -framework OpenCL -liconv -lSystem -lresolv -lc -lm -liconv
++ uname -s
+ '[' Darwin = Darwin ']'
++ uname -m
+ '[' arm64 = x86_64 ']'
++ git rev-parse HEAD
+ sed -e 's;@VERSION@;7912389334e347bbb2eac0520c836830875c39de;' -e 's;@PRIVATE_LIBS@; -lhwloc -framework OpenCL -framework OpenCL -framework OpenCL -framework OpenCL -framework OpenCL -framework OpenCL -framework OpenCL -framework OpenCL -framework OpenCL -framework OpenCL -framework OpenCL -liconv -lSystem -lresolv -lc -lm -liconv;' filcrypto.pc.template
+ find -L . -type f -name filcrypto.h
+ read
+ find -L . -type f -name libfilcrypto.a
+ read
+ exit
+ rm -f /var/folders/tt/tkhky6ws4yj097791hdbg0mr0000gn/T/tmp.KDtPwTgx
+ popd
~/Data/Projects/GoProjects/lotus_official/extern/filecoin-ffi
++ uname -s
+ '[' Darwin = Darwin ']'
++ uname -m
+ '[' arm64 = x86_64 ']'
+ find -L rust/target/release -type f -name libfilcrypto.a -exec cp -- '{}' . ';'
+ find -L rust -type f -name filcrypto.h -exec cp -- '{}' . ';'
+ find -L rust -type f -name filcrypto.pc -exec cp -- '{}' . ';'
+ pwd
/Users/jitash/Data/Projects/GoProjects/lotus_official/extern/filecoin-ffi
+ ls ./filcrypto.h ./filcrypto.pc ./filcrypto.yml ./install-filcrypto ./libfilcrypto.a
./filcrypto.h           ./filcrypto.pc          ./filcrypto.yml         ./install-filcrypto     ./libfilcrypto.a
+ check_installed_files
+ pwd
/Users/jitash/Data/Projects/GoProjects/lotus_official/extern/filecoin-ffi
+ ls ./filcrypto.h ./filcrypto.pc ./filcrypto.yml ./install-filcrypto ./libfilcrypto.a
./filcrypto.h           ./filcrypto.pc          ./filcrypto.yml         ./install-filcrypto     ./libfilcrypto.a
+ [[ ! -f ./filcrypto.h ]]
+ [[ ! -f ./libfilcrypto.a ]]
+ [[ ! -f ./filcrypto.pc ]]
+ echo '[install-filcrypto/main] successfully built and installed libfilcrypto from source'
[install-filcrypto/main] successfully built and installed libfilcrypto from source
+ exit
rm -f lotus
go build  -ldflags="-X=github.com/filecoin-project/lotus/build.CurrentCommit=+git.6fbaba132.dirty" -o lotus ./cmd/lotus
# github.com/zondax/hid
In file included from ../../../../go/pkg/mod/github.com/zondax/hid@v0.9.0/hid_enabled.go:38:
../../../../go/pkg/mod/github.com/zondax/hid@v0.9.0/hidapi/mac/hid.c:693:34: warning: 'kIOMasterPortDefault' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:123:19: note: 'kIOMasterPortDefault' has been explicitly marked deprecated here
rm -f lotus-miner
go build  -ldflags="-X=github.com/filecoin-project/lotus/build.CurrentCommit=+git.6fbaba132.dirty" -o lotus-miner ./cmd/lotus-miner
# github.com/zondax/hid
In file included from ../../../../go/pkg/mod/github.com/zondax/hid@v0.9.0/hid_enabled.go:38:
../../../../go/pkg/mod/github.com/zondax/hid@v0.9.0/hidapi/mac/hid.c:693:34: warning: 'kIOMasterPortDefault' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:123:19: note: 'kIOMasterPortDefault' has been explicitly marked deprecated here
rm -f lotus-worker
go build  -ldflags="-X=github.com/filecoin-project/lotus/build.CurrentCommit=+git.6fbaba132.dirty" -o lotus-worker ./cmd/lotus-seal-worker
# github.com/zondax/hid
In file included from ../../../../go/pkg/mod/github.com/zondax/hid@v0.9.0/hid_enabled.go:38:
../../../../go/pkg/mod/github.com/zondax/hid@v0.9.0/hidapi/mac/hid.c:693:34: warning: 'kIOMasterPortDefault' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:123:19: note: 'kIOMasterPortDefault' has been explicitly marked deprecated here
```

### Repo Steps

1. brew install go bzr jq pkg-config rustup hwloc
2. export LIBRARY_PATH=/opt/homebrew/lib
    export FFI_BUILD_FROM_SOURCE=1
3. make clean all
    '# github.com/zondax/hid
In file included from ../../../../go/pkg/mod/github.com/zondax/hid@v0.9.0/hid_enabled.go:38:
../../../../go/pkg/mod/github.com/zondax/hid@v0.9.0/hidapi/mac/hid.c:693:34: warning: 'kIOMasterPortDefault' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]'
...

**Comment by LanmpPython** [comment]
Hello, have you solved this problem? I also encountered this problem

**Comment by eirture** [comment]
I replaced the `kIOMasterPortDefault ` with `kIOMainPortDefault` at https://github.com/Zondax/hid/blob/master/hidapi/mac/hid.c#L693. It works for me. 

I found this solution in kovidgoyal/kitty#3719

**Comment by Reiers** [comment]
**Hi @jitash - Thanks for the report.** 

and thanks @eirture - I will add labels and assign it to the right team for analysis.

I have already reproduce the solution to the issue - and I built Lotus successfully with the small change in `hid.c`

```
rm -f lotus
go build  -ldflags="-X=github.com/filecoin-project/lotus/build.CurrentCommit=+git.e05fdf892" -o lotus ./cmd/lotus
rm -f lotus-miner
go build  -ldflags="-X=github.com/filecoin-project/lotus/build.CurrentCommit=+git.e05fdf892" -o lotus-miner ./cmd/lotus-miner
rm -f lotus-worker
go build  -ldflags="-X=github.com/filecoin-project/lotus/build.CurrentCommit=+git.e05fdf892" -o lotus-worker ./cmd/lotus-seal-worker
Caution: you have an existing lotus binary in your PATH. This may cause problems if you don't run 'sudo make install'
```

reiers@MacBook-Pro lotus % sudo make install
```
install -C ./lotus /usr/local/bin/lotus
install -C ./lotus-miner /usr/local/bin/lotus-miner
install -C ./lotus-worker /usr/local/bin/lotus-worker
```

reiers@MacBook-Pro lotus % lotus -v
`lotus version 1.13.2-rc4+mainnet+git.e05fdf892`

Reproduced solution on machine:
```
MacBook Pro (16-inch, 2021)
Apple M1 Max
64 GB RAM
```

**Comment by momack2** [comment]
@Reiers - is there an ETA on this fix? Hear this is still bothering folks on M1 macs...

**Comment by momack2** [comment]
Looks like there are install instructions for M1 chips here: https://lotus.filecoin.io/docs/set-up/install/#m1-based-cpus

**Comment by Reiers** [comment]
Sorry for the late reply @momack2 

I will reproduce tmr - and see if it its fixed now. If not, I will ask.
Thanks for flagging!

The instructions in our Docs is correct - but due to macOS 12>, there have been some changes. 
You have/had to go into a file a change kIOMasterPortDefault with kIOMainPortDefault for it to build correctly. 
_(it was/is that way for both Intel and M1 chips)_

**Comment by walkerlj0** [comment]
Tried installing this on Tue Mar 1 and still had to make the following changes:

`cd /Users/lindsayjowalker/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/zondax/hid@v0.9.0/hidapi/mac

sudo vim hid.c'

Found that file and still had to change kIOMaster to kIOMain on (I believe) was line 693)

**Comment by dragoonzx** [comment]
I make changes to the hid.c file, but the error remains the same. I'm not very familiar with go, maybe something else needs to be done?

**Comment by dragoonzx** [comment]
I made it. Full tutorial (from LexLuthr on Slack):
1. Delete everything from before. Remove any exported varibles for lotus build. 
2. xcode-select -p (if missing run xcode-select --install )
3. brew install go bzr jq pkg-config rustup hwloc
4. git clone https://github.com/filecoin-project/lotus.git
5. cd lotus/
6. git checkout tags/v1.14.1
7. export LIBRARY_PATH=/opt/homebrew/lib
8. export FFI_BUILD_FROM_SOURCE=1
9. rustup-init (default install)
10. Make sure ~/.lotus does not exists.
11. git submodule update --init
12. make all or make 2k depending upon what you are trying to build.

**Comment by walkerlj0** [comment]
@Reiers today on 6-6-2022 we are still getting issues with the KIOMaster port. This is from Parth Shah's new m1 Mac:
<img width="573" alt="Screen Shot 2022-06-06 at 1 25 13 PM" src="https://user-images.githubusercontent.com/66978602/172223469-c79b431f-c249-435c-891b-1cf3f818d7fc.png">

**Comment by Reiers** [comment]
Thanks to this PR https://github.com/filecoin-project/lotus/pull/9096 from @ianconsolata ❤️ 
You can install lotus from homebrew again ! 

`brew install filecoin-project/lotus/lotus` and `brew upgrade filecoin-project/lotus/lotus`

```
Mac Studio
reiers@M1Ultra-Protocol ~ % lotus -v
lotus version 1.17.0+mainnet+git.e120c9eaf

Macbook Pro
reiers@M1Max-Protocol ~ % lotus -v
lotus version 1.17.0+mainnet+git.e120c9eaf

iMac Pro 
reiers@IntelXeon-Protocol ~ % lotus -v
lotus version 1.17.0+mainnet+git.e120c9eaf
```

I have also verified that building from source does work as well!

If you are still experiencing problems - please open a new ticket or ask for help in our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions)

**Comment by ianconsolata** [comment]
So my homebrew fix doesn't actually solve this udnerlying issue

**Comment by CluEleSsUK** [comment]
I'm still having issues with this on m1 (12.5.1)

Following dragoonzx's post _mostly_ worked, but I also had to `export GO111MODULE=on` when using `go1.18.5 darwin/arm64`
