### ISSUE TITLE
(SnapDeals) Sectors stuck in FinalizeReplicaUpdate

### ISSUE THREAD

**Issue by Reiers** [filecoin-project/lotus#8225]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [X] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
Daemon:  1.14.2+mainnet+git.6347daf84+api1.5.0
Local: lotus version 1.14.2+mainnet+git.6347daf84
```

### Describe the Bug

I created 50 `SnapDealsWaitDeals` sectors.
I needed to restart the miner while a worker did PRU2 and where left with a sector stuck in limbo.
No matter what I try the sector is stuck:
 - Restarted the miner 
 - Restarted the worker with the files
 - Tried to move the sector out of WORK_PATH to see if at least failed.
 
 But nothing, nothing in miner logs.
 
```
miner:~$ lotus-miner sectors remove --really-do-it 20773
ERROR: normal shutdown of state machine

miner:~$ lotus-miner sectors terminate --really-do-it 20773
ERROR: normal shutdown of state machine

miner:~$ lotus-miner sectors abort-upgrade --really-do-it 20773
ERROR: normal shutdown of state machine

miner:~$ lotus-miner sectors update-state --really-do-it 20773 AbortUpgrade
ERROR: normal shutdown of state machine
```

Theres nothing I can do - so I will get slashed for that sector each wdPost. 

### Logging Information

```text
lotus-miner sectors status --log 20773
SectorID:	20773
Status:		FinalizeReplicaUpdate
CIDcommD:	baga6ea4seaqao7s73y24kcutaosvacpdjgfe5pw76ooefnyqw4ynr3d2y6x2mpq
CIDcommR:	bagboea4b5abcbo6noskdqgofj3dl74fd7a6sy4gbk5j3pyhcgtj4znwkljokw4c3
Ticket:		adebc14f4fa028ea0e3e20378c71aea04425b0c50ecdf2658fa48b4698cc656c
TicketH:	941170
Seed:		b6803e8523a251d663c9fd32eadbb93389b3cbcf03d16e94e082d4fa95fe1eb1
SeedH:		942646
Precommit:	bafy2bzaceclmubj6lfrrzwhzmllad7ilgytyz2p5cnoyjtias73cjq5qlj6iw
Commit:		bafy2bzaceaoxijwo4rheyncx2dynye7xee5jwf7shvbonm227hr3mo2wrkprs
Deals:		[4139222]
Retries:	0
--------
Event Log:
0.	2021-07-18 02:34:21 +0200 CEST:	[event;sealing.SectorStartCC]	{"User":{"ID":20773,"SectorType":8}}
1.	2021-07-18 02:35:20 +0200 CEST:	[event;sealing.SectorPacked]	{"User":{"FillerPieces":[{"Size":34359738368,"PieceCID":{"/":"baga6ea4seaqao7s73y24kcutaosvacpdjgfe5pw76ooefnyqw4ynr3d2y6x2mpq"}}]}}
2.	2021-07-18 02:35:20 +0200 CEST:	[event;sealing.SectorTicket]	{"User":{"TicketValue":"revBT0+gKOoOPiA3jHGuoEQlsMUOzfJlj6SLRpjMZWw=","TicketEpoch":941170}}
3.	2021-07-18 05:40:48 +0200 CEST:	[event;sealing.SectorPreCommit1]	{"User":{"PreCommit1Out":"eyJyZWdpc3RlcmVkX3Byb29mIjoiU3RhY2tlZERyZzMyR2lCVjFfMSIsImxhYmVscyI6eyJTdGFja2VkRHJnMzJHaUJWMSI6eyJsYWJlbHMiOlt7InBhdGgiOiIvbWVkaWEvdmVyb25pY2EvTE9UVVNfU1BBQ0UvTE9UVVNfV09SS0VSL2NhY2hlL3MtdDAyMjM1Mi0yMDc3MyIsImlkIjoibGF5ZXItMSIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL21lZGlhL3Zlcm9uaWNhL0xPVFVTX1NQQUNFL0xPVFVTX1dPUktFUi9jYWNoZS9zLXQwMjIzNTItMjA3NzMiLCJpZCI6ImxheWVyLTIiLCJzaXplIjoxMDczNzQxODI0LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9tZWRpYS92ZXJvbmljYS9MT1RVU19TUEFDRS9MT1RVU19XT1JLRVIvY2FjaGUvcy10MDIyMzUyLTIwNzczIiwiaWQiOiJsYXllci0zIiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvbWVkaWEvdmVyb25pY2EvTE9UVVNfU1BBQ0UvTE9UVVNfV09SS0VSL2NhY2hlL3MtdDAyMjM1Mi0yMDc3MyIsImlkIjoibGF5ZXItNCIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL21lZGlhL3Zlcm9uaWNhL0xPVFVTX1NQQUNFL0xPVFVTX1dPUktFUi9jYWNoZS9zLXQwMjIzNTItMjA3NzMiLCJpZCI6ImxheWVyLTUiLCJzaXplIjoxMDczNzQxODI0LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9tZWRpYS92ZXJvbmljYS9MT1RVU19TUEFDRS9MT1RVU19XT1JLRVIvY2FjaGUvcy10MDIyMzUyLTIwNzczIiwiaWQiOiJsYXllci02Iiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvbWVkaWEvdmVyb25pY2EvTE9UVVNfU1BBQ0UvTE9UVVNfV09SS0VSL2NhY2hlL3MtdDAyMjM1Mi0yMDc3MyIsImlkIjoibGF5ZXItNyIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL21lZGlhL3Zlcm9uaWNhL0xPVFVTX1NQQUNFL0xPVFVTX1dPUktFUi9jYWNoZS9zLXQwMjIzNTItMjA3NzMiLCJpZCI6ImxheWVyLTgiLCJzaXplIjoxMDczNzQxODI0LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9tZWRpYS92ZXJvbmljYS9MT1RVU19TUEFDRS9MT1RVU19XT1JLRVIvY2FjaGUvcy10MDIyMzUyLTIwNzczIiwiaWQiOiJsYXllci05Iiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvbWVkaWEvdmVyb25pY2EvTE9UVVNfU1BBQ0UvTE9UVVNfV09SS0VSL2NhY2hlL3MtdDAyMjM1Mi0yMDc3MyIsImlkIjoibGF5ZXItMTAiLCJzaXplIjoxMDczNzQxODI0LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9tZWRpYS92ZXJvbmljYS9MT1RVU19TUEFDRS9MT1RVU19XT1JLRVIvY2FjaGUvcy10MDIyMzUyLTIwNzczIiwiaWQiOiJsYXllci0xMSIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N31dLCJfaCI6bnVsbH19LCJjb25maWciOnsicGF0aCI6Ii9tZWRpYS92ZXJvbmljYS9MT1RVU19TUEFDRS9MT1RVU19XT1JLRVIvY2FjaGUvcy10MDIyMzUyLTIwNzczIiwiaWQiOiJ0cmVlLWQiLCJzaXplIjoyMTQ3NDgzNjQ3LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LCJjb21tX2QiOls3LDEyNiw5NSwyMjIsNTMsMTk3LDEwLDE0NywzLDE2NSw4MCw5LDIyNyw3MywxMzgsNzgsMTkwLDIyMywyNDMsMTU2LDY2LDE4MywxNiwxODMsNDgsMjE2LDIzNiwxMjIsMTk5LDE3NSwxNjYsNjJdfQ=="}}
4.	2021-07-18 06:07:44 +0200 CEST:	[event;sealing.SectorPreCommit2]	{"User":{"Sealed":{"/":"bagboea4b5abcbo6noskdqgofj3dl74fd7a6sy4gbk5j3pyhcgtj4znwkljokw4c3"},"Unsealed":{"/":"baga6ea4seaqao7s73y24kcutaosvacpdjgfe5pw76ooefnyqw4ynr3d2y6x2mpq"}}}
5.	2021-07-18 06:07:44 +0200 CEST:	[event;sealing.SectorPreCommitted]	{"User":{"Message":{"/":"bafy2bzaceclmubj6lfrrzwhzmllad7ilgytyz2p5cnoyjtias73cjq5qlj6iw"},"PreCommitDeposit":"28730488139620121","PreCommitInfo":{"SealProof":8,"SectorNumber":20773,"SealedCID":{"/":"bagboea4b5abcbo6noskdqgofj3dl74fd7a6sy4gbk5j3pyhcgtj4znwkljokw4c3"},"SealRandEpoch":941170,"DealIDs":[],"Expiration":2496550,"ReplaceCapacity":false,"ReplaceSectorDeadline":0,"ReplaceSectorPartition":0,"ReplaceSectorNumber":0}}}
6.	2021-07-18 06:11:00 +0200 CEST:	[event;sealing.SectorPreCommitLanded]	{"User":{"TipSet":"AXGg5AIgK0wrDr+uoKwJML/1t6roHPSKMWIbwIcDW0Qzji9X6kEBcaDkAiDw2OufCqLp5t6RnXSijMfEwK3IOHJkRRTzQ950HmfY5wFxoOQCINWzyse8J86t5hFpzWrOJnTTRxNVOVm0SwIA6n2p3X1NAXGg5AIgvqgfgavcIWhw+MApamc6OmVxYyTIxb5cYvRYWC9vJsABcaDkAiAIV8OYkbILoKUETVINho5OIMmV/1Jf+wz9f8bMG87H4QFxoOQCIKR97zb5frbiUg1ftaSf5Dpmadt2fMzHoqgonKajEkXZAXGg5AIgvAQYCrugihVcR2yC9jdpvR4Rwk2NzgD8YDxOe5K0TsA="}}
7.	2021-07-18 07:26:00 +0200 CEST:	[event;sealing.SectorSeedReady]	{"User":{"SeedValue":"toA+hSOiUdZjyf0y6tu5M4mzy88D0W6U4ILU+pX+HrE=","SeedEpoch":942646}}
8.	2021-07-18 07:48:57 +0200 CEST:	[event;sealing.SectorProofReady]	{"User":{"Proof":"s+mbD3A1Y4Ci9g7RfO/Bw09PMZejQJ4oNiBqw8gpaTImWWAslOCb2OGw8dr9lpwApYC23bpaCt0tKwaei66w9JVWq8HTFeXgBC90HdCfCSPeIqgKKxLna7kCt52hGgMYFkd7iHRxV850QXJ+mHvLeHJsGGnQ0rVpuMtpPY7FDHtC6aJTzK7du66aaF/1sicfjGyuBezeNY4rtsppipky9ixdI4J/9dhzG93uENHDycCIndG4VkCtUE2g3NDRkPCeiy562hYlbimjSoK7Lx3P6zSuTejsbvMKOfefiB+UCfKg6WTHz0AeSY2BiN21ig+TovIERkogKagSbg+6oNcX5IYFHTomR+HrSRH5ah9K19e/Ac0MoofODWm+vT15g437E/iXpUabWGayX+6rqTa3ePGIaOZ2fdwRqRsxGpsylD89khLQ9+pWtgjI22+p8CMBp4SFyr/iRZdFUfu9sHi17o1TW6Ya3al9dSa+L73PqhgX6LIj0XAQfo9vE8joIR6zpFu9ANu/I/6Gi7waIHbmfqjHrdEISyaMj/w/UxqAa8EfcEnuGz7JfcrrYzzMgxuaoChhHrxzPzfsfqGkTE0Hg6KC0jdZ62sKVeNDkE9xqDDI657kxJmer9wJy0G8GwVREvIfqFBP2HGeX4JlqWSI74z7v+rDDypd8h1wK6x9OFoQdhni4zDkxSW/RD++TLXglLKGGkSaUM0ERnqYHi0x9vmZDrkcHlMzy5m0vOQhZmGDgc2VjoUymPWWAFp0m0WVlkQt64yVMsd816jP9SDJU3D4PO2bf/mfdX1WY42T6CS4DxeGkguOGJKCqrd34kUioz1z0DjxamilOo6bTthMPiG3OgdQZCqRWtSVQfbhrJbx9W02KRu3v5HfFN4Q2GhEExaOhAZg/lUi6Hf/AFxA7xWqYKhjA8x/TVY2+T3JRu3gs9kqcShq562ctIW5nYwYozaGeX7o8GkRt8EuIL0X4UUW0AfUZspi0rSsUQpJqcU7DNl4CYpMt5iRWzXdPOYSithV4KMnwvydAty4ejDhyXqRzDNDHuQq/43rFrLdDqZtjxEERaS0+nJ1FsrhAkgeh/G7O6lsEB6l3kj12KHZnPA9YNvWff8rP2gvv09kb4F5G1TMDaxZcECx4VFLiU0nE512qUztqaoDV8QVzl62/uxra8MvY4sBRNFi8mVlX9MdhRNxPKA76VLxwuMpYy+OjZtKLV2rqA+Cr12zORNWJ8kgqPq0b5D0lYFDoB0Pjcg/xizUmG5cVvFna1GuszIPsGO8S+c0OhytcIIYG7nnjED+UhTlVb7gp81rTr6qSN05fVQtcS1dzkFR2bM9FGvhuXTaC2vnf7ebn8pTEWK/cbHEhk1Bq/5scyN0xkMSF0ohFX+vQgAyTUHjcFz0QM0MFsyBdG0EevpFYxSGot4qo4DA+uFm9LbH7KklKZ/5htFmF1t7Wox5fnembk4aoNGjrd3U9koyD7K6QhRAFF6KnOWxdRvxLjeniePIF4TVzrsF/rSg5czoaznt4EUX5oQMt03dN5HJeL8i4wOXeC1T2nZjMyXb0rZev4r6GQOhhjZzCunwp0BGla3Z1aAOy7MAioQXK9O9s3iQdbkl78ga44yguOfRtVZY0KcWy5n8WUG3KMfMKdVoa3o6JiMQ2ysUDWNO+eV7WkZ+n5NPoeRPQGUeYpA28q8PnqkfhmFcjjPwRvTSBw66/9ydhQInGmuzgsMjHhZTvAb+MqSKtvSNTD1sivLIFdfNrv6lU+Wy2YomkF4Zn3U3SK7kzLRGZtlzozvdAPINtxLDyWw2pwsufHJkw/FuUMj1dX4KSshsR3mEoYsTF+OW5gVUI1GZ08uemT2dNR1NXsy5EVI1dwRf9IQvDG0Dh9MQNFnZV7FMze6rjDxYi1XoPq4WmMPHRqpeFjl+lvruhTs+q3vWRYZ+/gmCbbR38bGcKrHs11EPKCPl1XPXl1Zs+PkEWpz/pKlHlJlMq0TuzV3oWdnI70TjkBIypwKZiyBRzf9wYjFdqAJeDquv5QSjY3CFMWE/K26Qs8bI4v6sCFk8ILy/C26H2dVbh+Mb9oGHO07BLfZikXgb07Ajt+GrIxJACJoY2eRphXeuB4eGp5QsfmlVoLkzxd2VD4mq3AuXdVn96iAdQqfhjq1PBcfaKTfHQPoL43lLFssArYOgRzYm/2CcrXpDYGSdK230m/opzIsGI/uB+/PoNrlnZd7EaZ3C+Npt32Lbr6GckooQNppVKMYDuScdKeuxrnYi/RxvJm3KRr+XONJN8OkbHyAzdlEWQPsjet5atqQRvEzLJuRG98zTIYTSAYpYPPMh9PxoEGOwJtecjxpSgyzWtFco0HEzbxunrhd7lU+BZcWHP7W08Xxxop3PcgI1YmPreuBySmudv39LIlBp7J3lne+pWg34TeD2S4pcCu75gZ1HmLkLvVMwH+fSkXZQERVvTpI299jUuWnhFc9JZgVAUQgH1I/PtWyriTDEtOcU2ZPKPpYCHtvw2QP3pIqCwNW2Qm1NLJbjmyu7LAQ34leTxB3hNHIz6lktSp/y"}}
9.	2021-07-18 07:51:11 +0200 CEST:	[event;sealing.SectorFinalized]	{"User":{}}
10.	2021-07-18 07:51:16 +0200 CEST:	[event;sealing.SectorCommitSubmitted]	{"User":{"Message":{"/":"bafy2bzaceaoxijwo4rheyncx2dynye7xee5jwf7shvbonm227hr3mo2wrkprs"}}}
11.	2021-07-18 07:55:30 +0200 CEST:	[event;sealing.SectorProving]	{"User":{}}
12.	2021-07-18 07:55:30 +0200 CEST:	[event;sealing.SectorFinalized]	{"User":{}}
13.	2022-03-01 16:52:06 +0100 CET:	[event;sealing.SectorStartCCUpdate]	{"User":{}}
14.	2022-03-01 18:41:00 +0100 CET:	[event;sealing.SectorAddPiece]	{"User":{}}
15.	2022-03-01 18:46:23 +0100 CET:	[event;sealing.SectorPieceAdded]	{"User":{"NewPieces":[{"Piece":{"Size":34359738368,"PieceCID":{"/":"baga6ea4seaqgt5ywdey6ndkbxcmyxbwjqfuf5mmhnx3pcfhaww23mso7sldm4eq"}},"DealInfo":{"PublishCid":{"/":"bafy2bzaceb2jdla4gzfeosdpckfo66g3ulx7koq3r2uq53s2mdt64vr7x3hmk"},"DealID":4139222,"DealProposal":{"PieceCID":{"/":"baga6ea4seaqgt5ywdey6ndkbxcmyxbwjqfuf5mmhnx3pcfhaww23mso7sldm4eq"},"PieceSize":34359738368,"VerifiedDeal":true,"Client":"f17ia7m5mvizrdug3sqtevqw3tifiqvxqr3kdaeuq","Provider":"f022352","Label":"Qmf7wUFqtBTeXTUrnAzNieqxxbEa4ksd2PC8Jv1u4UqywK","StartEpoch":1609385,"EndEpoch":3055270,"StoragePricePerEpoch":"0","ProviderCollateral":"5479905071311194","ClientCollateral":"0"},"DealSchedule":{"StartEpoch":1609385,"EndEpoch":3055270},"KeepUnsealed":true}}]}}
16.	2022-03-01 18:46:23 +0100 CET:	[event;sealing.SectorStartPacking]	{"User":{}}
17.	2022-03-01 18:46:23 +0100 CET:	[event;sealing.SectorPacked]	{"User":{"FillerPieces":null}}
18.	2022-03-01 18:53:55 +0100 CET:	[event;sealing.SectorReplicaUpdate]	{"User":{"Out":{"NewSealed":{"/":"bagboea4b5abcbfedf2r7xtaapzso3kiowhoqsbwbk4ztkjubetkcbkhhmwugdlsf"},"NewUnsealed":{"/":"baga6ea4seaqgt5ywdey6ndkbxcmyxbwjqfuf5mmhnx3pcfhaww23mso7sldm4eq"}}}}
19.	2022-03-01 19:08:14 +0100 CET:	[event;sealing.SectorProveReplicaUpdate]	{"User":{"Proof":"mUAnZISTbIXZD67XjzC4xENeD43Njhik1AhVUn6taMG6OxBGHDgsVeBqHvinBHYbswDud/QJb6jCGLSM9b0BHfcw00we9xV6P/+ykXv8j3pBBcGQ01He52L4VBRNLWq6BsPN1sO8fqqPltBVuySg+NerNIPIXeJp1IDcerHAZrEXtpTzuYL2QLPr+Zrk8ubqgeAQwQy7naqle+e3il9QI/liV2DFWjnOx9TRcNeHMo+ov4r56EUTBi78j0mHZb2Eqag1sR9H3xtptw8uy8Dh/fsz37nqloZb89hR8jFWJl88Q/VWsyvEYttkeDctKqKWpM3gfuZbUzYzMEo/Kybdy1SAAObG+z+4O6RT999wessB4bVfOG/v1l6vcf7WpgpQDnBzxYRXm6do7bWZU8z0v0Cz7eXU+C0+gnRrY+Tdh+OvRA/kP2Z+s6llKfhmw/UgioJ9o296uPw+obzOlankuktAgjXpijaruPT7dACDqc6MrzeWYPTttZYEKlUJwPtzlmsGdXwi9AdZYIT5QwH5UHRthDFsThFUjb3JEQ8xL7TlTh28Q3I9Q6oHkRrR0kwRrc/bBRa8atd8DV5iSoVx2LTWCA+ntRZIYhmpqNxcLWIYlnzHWkUitbnPA8Ezz4lFCQ/1dTdUvGB26q5Fx2tj0OD6mdSC4Pg2/oqEGiAYL4tBBMv7DphbAa0UgJ1z4p2Bl+4+/MrP1oC7TzVjyUFNDQWaeC3A6oaNLzAI0jg8ySIDRay/3IVKGD6Yj7ksnjJ+tQAjsumolyEIJvQmX4ofIxIZRPFd7h3QeUFgPjxzwXKnP7AILWj+z4EeiyQK8lE6jrCfQx+jsRJV/9Nf+iGdjtTm/uP+YKaglB4hKWck+89EMslgizOGUJTKeJ9UCyShEhYWj8WINoIDMHfghLAM/SM3rM+CDPlPPQS2+TFvP85p0rArO5jzDy8xWNc8GSGpgJYOro2vtBbn/n1OIHSF4Eh2OlanfrMwYWLNNbSZbF1iwnBrneAAqvNwMTje94h2kGljZ1xYU/Mbv6eQtmQ55rAReRDvg5ACjCQG419No+vpTPdFl8RgfCy6s4iLzEqlmSF46qgTIUKMXyzTMS2KMV6LUkxsNW80l9C3QUymsV5zK5Kdh8fHvkAFkbWieZWTAvg6xcwjKpHSUIlrIN7ou5XZ4cZwiW1X3vtYuQB4GEHjeljMb9MEDHdaACskDP6LiivEJJdGFGAyHwdXlOozE6BerfNybspbvYJvuBTulY4sQZ+Yinibw89aFodFOa9Mriad6H0WOGkk6x1gOQenSvY+dLF5zvi3cCevvJRpHUmtNISMKLsobqs+UEMHB4Qiuf+gSmtjE2oR7GL0N1KBIDT2YdQ6Epw6Alb19Dj48STLF9v0fA2qhTwrFwfi4O1TGSLZxKhceS76rO8zLedKKBDOjLks5OsuKsxlS/yv9+X7NRmWzi5RSpA4jcSWTL59kqTx21HWYhrnPVXUICutTqf7OI3dSNch9aCG+uidjTwB0k+le1UFRngHxTI0Y2YPrlNG6orsTqtHK+WyTPMvRibJWbZ+S89IA0DCniW7U24eXNZS3L++CeClkaBAdsLTqDXxeKZF+B8er/lc91ClGVw9P1Gb3sFpcFmJfMx8TNM0LvXBJgSMucQIa40kP9t1Eyoh/TAjUS5l2sixSZ25w40bLSNBM8rYai6fJh0S3S6tVJLRqm2RKiRnwVjItKg9kSi5dd33U3jGNY8YPhCVd5weroOs+QkTTmNq+4dV778Mf5vMKzNHpu0e6Ph05xyRtCNiwE7BezWKeoACPTTWizZ6yUz/fVhcqN9YKWUedR08eHR04ToNE+4bLdWgPvlQtPU9bmgijhp10ng/0UK0897G/Kf+pCE90SNyDMGIiwdYkOKHIW842qbpDi8hOUSyD/0I9KVQHSax1e1Hry2YeYVoz2IyBBa4QIWdLxbRSqRM+i4AgsPBa2vwpSXWRuo9uL287cfotGUrOieSWZjCvNSJILwl3DNeuWfKKgiaCGmQ72UyUwyAaSlxAs8YVn8ppcG2j/ZB3jjV8qMN4BBIEAlgVwSaMDxwKSNdZCIocmb1fVRtL13beL8jEkmHZBvPjONkzy2tvMrUjPb7knGF7UcNRpaHTHU4Zmx2pFbwkjy8+Xw94BUBT0BOYaTm3GUFDHAhr4PWStHSHSFH+wMpqRsBI7D8PVtwaLMZj0a21TZzkBd/4g0BhoR5IOjY+eqeqc3FEGFZYP1QUj5B3a59T9cvnrkrRMmJ+5MQZv+Aw9ncY4FUux8LvRPhtM8uZOc1sU9elcUCzSRCBFLslG/+x+PzVOMjYhJ3lcX+7qul5noc+Fp59ClIAOKU0+vquwkojmnnFnhM/881cOZCla7pu3G2hmiOkgwyQUg27HFrWIo3Ptqb2uYb6fKzByY5VxdODl/6isp7G5oUchYCLOZqW7mY3xFPn0fdfYfc1hN6ANMJvKALeEvNk8Nit4xA9jIPkx/dqZx4CexsXVeImgUDqVzH+kyLgbxHM2kTn0HvQtjfbhZnsTgdR8vBNxPqiz4soE5efQ3wGSVeFZ+CC+uYKcSpKTb2Kmih4KZw+WX0gEHfpa8VdmYRDomk/fJx6+91k5nGbfstJwX9/9RvMWuSnzjpwgaGk7ZQ57p5SuKYkaEj7rmbSFWUhfTChOwYxudyEKzl5QH6bomwn4j6CBdD9aF1KgfigW9jsBFhuTPzVbhHrpXOmZiCLBPV8VgUZNmPiF1H0qHile41Jmd496trmkaS/N4Tz/uzGKhs9JcU1XfaIm13F2jT8Bk8f5BEXbcCrKw8NLAM/IvFzDPMclsKNPNsCiq4316IwajtANqa4WPQVfJTGeA/iRhHicHurUrvivJizvqmUUPRVT46MrOM/rmjd4H5YHPC92pAjAR/Ho5dqq0iTDz3FgSjRNugOSAVGI6ny8VKdbV0xdjr96AF+da2EL51NOQCexamrqoA2sBJ9zw/cV9e/EOH7SiDLvvpqV4WToT2V6pEJz2hENfPiQshT5UGLZmS/x3FyX9hB7ZJr8ZMxFBlcz9+CI/OI/9KjnlsEZ8PqNoFf9UWQPIIe+Rsvao/L9k1btosYjYIJMwX90zIqUHFA0333kzA5SWalcpPKMWKowRGAdRZZbps3zL5ORf9Di7teH74Fu6hqjnLoDKJYaPYm+vYjec6n8x0Eis6cR354VARCt2ubeT5hlNtXdNPtevXGorR+SjyiKg4bPH6Ec3y3d0j5s+VMSiHlG4PqFjVw2BW9ueoZ3AY9qH1UnNPS+YHuahIs9DFRRhec24raIgCVyVoortOfLeHlVVOM/45m/OEtihbgv/5MaszDbuL8T8owDIQQZqdrNepJruDiC8x6QI5M6sZue+prWlgv98cQuq3Thx0P2O78yiHpMfjKGmMXOyOU0p7AUCD3YHWkekWOuXxL2r755eXBrFnFjxY3yjZMWtln5cFVUTv8SUbtnuqd3Ar8hhKXaO9gVmZLzXotxjodKkhc98cklKbvY/vk9sFqIRyM2eFXZ6xw8G+RV+wibMJ7OFbGqX7LDklNV/Df2hOzG6uDUpglo/Pr7TM/yOQ/GLw+tEfjB9q+l2F3rTgkR8GIbrrtcV6S/wZfA70Dxiqs3umsLIZl6RnaRGnNDnR5gXNSDZfAU9Yp74o3KKc87Kx7kaX1d0M/xaeVplyP4lKPaAHB79HAKNliq4Sxp83Ic3jGWwacO3ITAuHmDXR0oU/QV4D++zltRNgEHO2hCRGAZKVC2KWhYEWcOKZBHyaai4rhl5XSYXPgBUSUwergzgyFpXU05PMwzCJG8ENqp04PtwHmlgGmc3hVShhqLPWjmOTyWbR8mGQ2uCfoDWs7L76GOVdvvGLqRDC64rA9KEqfW843yiekBfD3Vy8WbDNeoqWXNpPpsKurmSQ9ZAozr6iA5RjGFe+2senN7xJp2BCWhiIJSM5GE00IzSgKqG2NZ6VmeEOo6QbSuUu+s7d+LymqFdGM/YAyUe53fyqBXaMxahjo9lpkkp2MqrKAkUo61VmiWgHsj8uIEzKCZl47aFrKiU3PmG690YKm+8B4ivZH5+9x018"}}
20.	2022-03-01 19:08:14 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
21.	2022-03-01 19:09:14 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
22.	2022-03-01 19:09:14 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
23.	2022-03-01 19:10:14 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
24.	2022-03-01 19:10:14 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
25.	2022-03-01 19:11:14 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
26.	2022-03-01 19:11:14 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
27.	2022-03-01 19:12:14 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
28.	2022-03-01 19:12:14 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
29.	2022-03-01 19:13:14 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
30.	2022-03-01 19:13:14 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
31.	2022-03-01 19:14:14 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
32.	2022-03-01 19:14:14 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
33.	2022-03-01 19:15:14 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
34.	2022-03-01 19:15:14 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
35.	2022-03-01 19:16:14 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
36.	2022-03-01 19:16:14 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
37.	2022-03-01 19:17:14 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
38.	2022-03-01 19:17:14 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
39.	2022-03-01 19:18:14 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
40.	2022-03-01 19:18:14 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
41.	2022-03-01 19:19:14 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
42.	2022-03-01 19:19:14 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
43.	2022-03-01 19:20:14 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
44.	2022-03-01 19:20:14 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
45.	2022-03-01 19:21:14 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
46.	2022-03-01 19:21:14 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
47.	2022-03-01 19:22:14 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
48.	2022-03-01 19:22:14 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
49.	2022-03-01 19:23:14 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
50.	2022-03-01 19:23:14 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
51.	2022-03-01 19:24:14 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
52.	2022-03-01 19:24:14 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
53.	2022-03-01 19:25:14 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
54.	2022-03-01 19:25:14 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
55.	2022-03-01 19:26:14 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
56.	2022-03-01 19:26:14 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
57.	2022-03-01 19:27:14 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
58.	2022-03-01 19:27:14 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
59.	2022-03-01 19:28:14 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
60.	2022-03-01 19:28:14 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
61.	2022-03-01 19:29:14 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
62.	2022-03-01 19:29:14 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
63.	2022-03-01 19:30:14 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
64.	2022-03-01 19:30:14 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
65.	2022-03-01 19:31:14 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
66.	2022-03-01 19:31:14 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
67.	2022-03-01 19:32:14 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
68.	2022-03-01 19:32:14 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
69.	2022-03-01 19:33:14 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
70.	2022-03-01 19:33:14 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
71.	2022-03-01 19:34:14 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
72.	2022-03-01 19:34:14 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
73.	2022-03-01 19:35:14 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
74.	2022-03-01 19:35:14 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
75.	2022-03-01 19:36:14 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
76.	2022-03-01 19:36:14 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
77.	2022-03-01 19:37:14 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
78.	2022-03-01 19:37:14 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
79.	2022-03-01 19:38:14 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
80.	2022-03-01 19:38:14 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
81.	2022-03-01 19:39:14 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
82.	2022-03-01 19:39:14 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
83.	2022-03-01 19:40:14 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
84.	2022-03-01 19:40:14 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
85.	2022-03-01 19:41:14 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
86.	2022-03-01 19:41:14 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
87.	2022-03-01 19:44:25 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
88.	2022-03-01 19:44:52 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
89.	2022-03-01 19:45:52 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
90.	2022-03-01 19:45:52 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
91.	2022-03-01 19:46:52 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
92.	2022-03-01 19:46:52 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
93.	2022-03-01 19:47:52 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
94.	2022-03-01 19:47:52 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
95.	2022-03-01 19:48:52 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
96.	2022-03-01 19:48:52 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
97.	2022-03-01 19:49:52 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
98.	2022-03-01 19:49:52 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
99.	2022-03-01 19:50:52 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
100.	2022-03-01 19:50:52 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
101.	2022-03-01 19:51:52 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
102.	2022-03-01 19:51:52 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
103.	2022-03-01 19:52:52 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
104.	2022-03-01 19:52:52 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
105.	2022-03-01 19:53:52 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
106.	2022-03-01 19:53:52 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
107.	2022-03-01 19:54:52 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
108.	2022-03-01 19:54:52 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
109.	2022-03-01 19:55:52 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
110.	2022-03-01 19:55:52 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
111.	2022-03-01 19:56:52 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
112.	2022-03-01 19:56:52 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
113.	2022-03-01 19:57:52 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
114.	2022-03-01 19:57:52 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
115.	2022-03-01 19:58:52 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
116.	2022-03-01 19:58:52 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
117.	2022-03-01 19:59:52 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
118.	2022-03-01 19:59:52 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
119.	2022-03-01 20:00:52 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
120.	2022-03-01 20:00:52 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
121.	2022-03-01 20:01:52 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
122.	2022-03-01 20:01:52 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
123.	2022-03-01 20:02:52 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
124.	2022-03-01 20:02:52 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
125.	2022-03-01 20:03:52 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
126.	2022-03-01 20:03:52 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
127.	2022-03-01 20:04:52 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
128.	2022-03-01 20:04:52 +0100 CET:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
129.	2022-03-01 20:05:52 +0100 CET:	[event;sealing.SectorRetrySubmitReplicaUpdate]	{"User":{}}
130.	2022-03-01 20:05:52 +0100 CET:	[event;sealing.SectorReplicaUpdateSubmitted]	{"User":{"Message":{"/":"bafy2bzaceckea32lfuorgm7cv2bifaiynpbpgkbxfppfx7vzd4xtlzr7virga"}}}
131.	2022-03-01 20:09:00 +0100 CET:	[event;sealing.SectorReplicaUpdateLanded]	{"User":{}}
```

### Repo Steps

SnapUp a lot of sectors, restart miner process, and some might be stuck.

**Comment by scaseye** [comment]
I was in the process of sealing 32 sectors, figured I would try to snap 2 sectors….

`lotus-miner version 1.14.1+mainnet+git.d2dca7b21`

```
lotus-miner sectors snap-up 3837
lotus-miner sectors snap-up 3490
```

```
==> logs/miner.log <==
{"level":"info","ts":"2022-03-01T16:24:29.992-0800","logger":"sectors","caller":"storage-sealing/input.go:396","msg":"CC update sector {1611097 3837} cannot fit deal, expiration 3056878 before deal end epoch 3121909"}
{"level":"info","ts":"2022-03-01T16:24:29.993-0800","logger":"sectors","caller":"storage-sealing/input.go:396","msg":"CC update sector {1611097 3490} cannot fit deal, expiration 3037402 before deal end epoch 3121909"}
```

I obviously did not extend the sectors properly prior to the snap-up command… what caused me to panic was that my entire queue of verified deals was now blocked.  New deals were being imported, but then got stuck in Staged state.  My panic caused me to do the following…

```
lotus-miner sectors abort-upgrade 3837
lotus-miner sectors abort-upgrade 3490
```

Reverted the sectors to CC. However in the logs I kept seeing the following messages even though there was no SnapDeals waiting…?  You can see below where I ran the abort.

```
{"level":"info","ts":"2022-03-01T16:35:13.447-0800","logger":"sectors","caller":"storage-sealing/input.go:530","msg":"aborting upgrade of sector","sector":"3837","trigger":"user"}
{"level":"warn","ts":"2022-03-01T16:35:13.448-0800","logger":"sectors","caller":"storage-sealing/fsm.go:733","msg":"sector 3837 got error event sealing.SectorAbortUpgrade: triggered by user"}
{"level":"info","ts":"2022-03-01T16:35:13.452-0800","logger":"sectors","caller":"storage-sealing/input.go:396","msg":"CC update sector {1611097 3837} cannot fit deal, expiration 3056878 before deal end epoch 3121909"}
{"level":"info","ts":"2022-03-01T16:35:13.454-0800","logger":"sectors","caller":"storage-sealing/input.go:396","msg":"CC update sector {1611097 3837} cannot fit deal, expiration 3056878 before deal end epoch 3121909"}
{"level":"info","ts":"2022-03-01T16:35:13.456-0800","logger":"sectors","caller":"storage-sealing/input.go:396","msg":"CC update sector {1611097 3837} cannot fit deal, expiration 3056878 before deal end epoch 3121909"}
{"level":"info","ts":"2022-03-01T16:35:13.458-0800","logger":"sectors","caller":"storage-sealing/input.go:396","msg":"CC update sector {1611097 3837} cannot fit deal, expiration 3056878 before deal end epoch 3121909"}
{"level":"info","ts":"2022-03-01T16:35:13.460-0800","logger":"sectors","caller":"storage-sealing/input.go:396","msg":"CC update sector {1611097 3837} cannot fit deal, expiration 3056878 before deal end epoch 3121909"}
{"level":"error","ts":"2022-03-01T16:35:13.460-0800","logger":"sectors","caller":"storage-sealing/input.go:457","msg":"we are trying to create a new sector with open sectors map[{1611097 3490}:0xc015887980 {1611097 3837}:0xc03610fae0]"}
```
… those messages above continue in the logs till I did the following.

```
lotus-miner sectors extend --new-expiration 3124800 3837
lotus-miner sectors match-pending-pieces
```

```
{"level":"debug","ts":"2022-03-01T22:49:30.525-0800","logger":"advmgr","caller":"sector-storage/sched.go:467","msg":"SCHED try assign sqi:0 sector 3837 to window 13"}
{"level":"debug","ts":"2022-03-01T22:49:30.525-0800","logger":"advmgr","caller":"sector-storage/sched.go:476","msg":"SCHED ASSIGNED sqi:0 sector 3837 task seal/v0/addpiece to window 13"}
{"level":"debug","ts":"2022-03-01T22:49:30.525-0800","logger":"advmgr","caller":"sector-storage/sched_worker.go:375","msg":"assign worker sector 3837"}
{"level":"info","ts":"2022-03-01T22:51:07.680-0800","logger":"sectors","caller":"storage-sealing/input.go:237","msg":"deal added to a sector","deal":4149724,"sector":"3837","piece":"baga6ea4seaqhcrcgthsmiqv3ky7evyfer2qofyn4d7g5yy4urjhqwacrnf7okjq"}
{"level":"info","ts":"2022-03-01T22:51:07.682-0800","logger":"sectors","caller":"storage-sealing/input.go:110","msg":"starting to seal deal sector","sector":"3837","trigger":"filled"}
{"level":"info","ts":"2022-03-01T22:51:07.684-0800","logger":"sectors","caller":"storage-sealing/states_sealing.go:48","msg":"performing filling up rest of the sector...","sector":"3837"}
{"level":"debug","ts":"2022-03-01T22:51:07.737-0800","logger":"advmgr","caller":"sector-storage/sched.go:467","msg":"SCHED try assign sqi:0 sector 3837 to window 12"}
{"level":"debug","ts":"2022-03-01T22:51:07.737-0800","logger":"advmgr","caller":"sector-storage/sched.go:476","msg":"SCHED ASSIGNED sqi:0 sector 3837 task seal/v0/replicaupdate to window 12"}
{"level":"debug","ts":"2022-03-01T22:51:07.737-0800","logger":"advmgr","caller":"sector-storage/sched_worker.go:375","msg":"assign worker sector 3837"}
{"level":"debug","ts":"2022-03-01T22:52:48.648-0800","logger":"stores","caller":"stores/http_handler.go:154","msg":"served sector file/dir, sectorID={Miner:1611097 Number:3837}, fileType=sealed, path=/mnt/cephfs/mainnet32GiB/storage/sealed/s-t01611097-3837"}
{"level":"debug","ts":"2022-03-01T22:52:49.400-0800","logger":"stores","caller":"stores/http_handler.go:154","msg":"served sector file/dir, sectorID={Miner:1611097 Number:3837}, fileType=cache, path=/mnt/cephfs/mainnet32GiB/storage/cache/s-t01611097-3837"}
{"level":"debug","ts":"2022-03-01T22:58:35.163-0800","logger":"advmgr","caller":"sector-storage/sched.go:467","msg":"SCHED try assign sqi:0 sector 3837 to window 17"}
{"level":"debug","ts":"2022-03-01T22:58:35.163-0800","logger":"advmgr","caller":"sector-storage/sched.go:476","msg":"SCHED ASSIGNED sqi:0 sector 3837 task seal/v0/provereplicaupdate/1 to window 17"}
{"level":"debug","ts":"2022-03-01T22:58:35.163-0800","logger":"advmgr","caller":"sector-storage/sched_worker.go:375","msg":"assign worker sector 3837"}
{"level":"debug","ts":"2022-03-01T22:58:36.636-0800","logger":"advmgr","caller":"sector-storage/sched.go:467","msg":"SCHED try assign sqi:0 sector 3837 to window 21"}
{"level":"debug","ts":"2022-03-01T22:58:36.636-0800","logger":"advmgr","caller":"sector-storage/sched.go:476","msg":"SCHED ASSIGNED sqi:0 sector 3837 task seal/v0/provereplicaupdate/2 to window 21"}
{"level":"debug","ts":"2022-03-01T22:58:36.636-0800","logger":"advmgr","caller":"sector-storage/sched_worker.go:375","msg":"assign worker sector 3837"}
{"level":"debug","ts":"2022-03-01T23:28:59.982-0800","logger":"advmgr","caller":"sector-storage/sched.go:467","msg":"SCHED try assign sqi:0 sector 3837 to window 16"}
{"level":"debug","ts":"2022-03-01T23:28:59.982-0800","logger":"advmgr","caller":"sector-storage/sched.go:476","msg":"SCHED ASSIGNED sqi:0 sector 3837 task seal/v0/finalize/replicaupdate to window 16"}
{"level":"debug","ts":"2022-03-01T23:28:59.982-0800","logger":"advmgr","caller":"sector-storage/sched_worker.go:375","msg":"assign worker sector 3837"}
{"level":"debug","ts":"2022-03-01T23:29:06.764-0800","logger":"advmgr","caller":"sector-storage/sched.go:467","msg":"SCHED try assign sqi:0 sector 3837 to window 11"}
{"level":"debug","ts":"2022-03-01T23:29:06.764-0800","logger":"advmgr","caller":"sector-storage/sched.go:476","msg":"SCHED ASSIGNED sqi:0 sector 3837 task seal/v0/fetch to window 11"}
{"level":"debug","ts":"2022-03-01T23:29:06.764-0800","logger":"advmgr","caller":"sector-storage/sched_worker.go:375","msg":"assign worker sector 3837"}
{"level":"info","ts":"2022-03-01T23:29:06.766-0800","logger":"stores","caller":"stores/remote.go:229","msg":"Fetch http://40.0.0.200:14001/remote/unsealed/s-t01611097-3837 -> /mnt/cephfs/mainnet32GiB/storage/unsealed/fetching/s-t01611097-3837"}
{"level":"debug","ts":"2022-03-01T23:29:45.449-0800","logger":"stores","caller":"stores/util_unix.go:30","msg":"move sector data","from":"/mnt/cephfs/mainnet32GiB/storage/unsealed/fetching/s-t01611097-3837","to":"/mnt/cephfs/mainnet32GiB/storage/unsealed/s-t01611097-3837"}
{"level":"info","ts":"2022-03-01T23:29:45.452-0800","logger":"stores","caller":"stores/remote.go:374","msg":"Delete http://40.0.0.200:14001/remote/unsealed/s-t01611097-3837?keep=b792b0e8-fa41-4e4f-a7f2-74714e0ca9ff"}
{"level":"info","ts":"2022-03-01T23:29:49.252-0800","logger":"stores","caller":"stores/remote.go:229","msg":"Fetch http://40.0.0.200:14001/remote/update/s-t01611097-3837 -> /mnt/cephfs/mainnet32GiB/storage/update/fetching/s-t01611097-3837"}
{"level":"error","ts":"2022-03-01T23:29:49.256-0800","logger":"evtsm","caller":"go-statemachine@v1.0.1/machine.go:86","msg":"Executing event planner failed: running planner for state FinalizeReplicaUpdate failed:\n    github.com/filecoin-project/lotus/extern/storage-sealing.(*Sealing).plan\n        /home/scaseye/lotus/extern/storage-sealing/fsm.go:382\n  - planner for state FinalizeReplicaUpdate received unexpected event sealing.SectorFinalizeFailed ({User:finalize sector: moving sector to storage: storage call error 0: failed to acquire sector {1611097 3837} from remote (tried [{c7855dca-fca8-4c5f-ab1e-4f5ec8368c03 [http://40.0.0.200:14001/remote/update/s-t01611097-3837] 10 true false false}]): 1 error occurred:\n    \t* fetch error http://40.0.0.200:14001/remote/update/s-t01611097-3837 (storage c7855dca-fca8-4c5f-ab1e-4f5ec8368c03) -> /mnt/cephfs/mainnet32GiB/storage/update/fetching/s-t01611097-3837: non-200 code: 500\n    \n    }):\n    github.com/filecoin-project/lotus/extern/storage-sealing.planOne.func1\n        /home/scaseye/lotus/extern/storage-sealing/fsm.go:750"}
```

Restarted Miner and Markets…

```
{"level":"warn","ts":"2022-03-02T06:17:02.695-0800","logger":"stores","caller":"stores/index.go:246","msg":"sector {1611097 3837} redeclared in b792b0e8-fa41-4e4f-a7f2-74714e0ca9ff"}
{"level":"warn","ts":"2022-03-02T06:17:03.745-0800","logger":"stores","caller":"stores/index.go:246","msg":"sector {1611097 3837} redeclared in b792b0e8-fa41-4e4f-a7f2-74714e0ca9ff"}
{"level":"warn","ts":"2022-03-02T06:17:04.884-0800","logger":"stores","caller":"stores/index.go:246","msg":"sector {1611097 3837} redeclared in b792b0e8-fa41-4e4f-a7f2-74714e0ca9ff"}
{"level":"debug","ts":"2022-03-02T06:17:04.897-0800","logger":"advmgr","caller":"sector-storage/sched.go:467","msg":"SCHED try assign sqi:0 sector 3837 to window 0"}
{"level":"debug","ts":"2022-03-02T06:17:04.897-0800","logger":"advmgr","caller":"sector-storage/sched.go:476","msg":"SCHED ASSIGNED sqi:0 sector 3837 task seal/v0/finalize/replicaupdate to window 0"}
{"level":"debug","ts":"2022-03-02T06:17:04.898-0800","logger":"advmgr","caller":"sector-storage/sched_worker.go:375","msg":"assign worker sector 3837"}
{"level":"error","ts":"2022-03-02T06:17:04.900-0800","logger":"evtsm","caller":"go-statemachine@v1.0.1/machine.go:86","msg":"Executing event planner failed: running planner for state FinalizeReplicaUpdate failed:\n    github.com/filecoin-project/lotus/extern/storage-sealing.(*Sealing).plan\n        /home/scaseye/lotus/extern/storage-sealing/fsm.go:382\n  - planner for state FinalizeReplicaUpdate received unexpected event sealing.SectorFinalizeFailed ({User:finalize sector: storage call error 0: failed to acquire sector {1611097 3837} from remote(8): sector not found}):\n    github.com/filecoin-project/lotus/extern/storage-sealing.planOne.func1\n        /home/scaseye/lotus/extern/storage-sealing/fsm.go:750"}
```

**Comment by Reiers** [comment]
Tested and Confirmed.
This issue is fixed in the latest release of lotus:
https://github.com/filecoin-project/lotus/releases/tag/v1.14.4
Closing issue ticket.

**Comment by benjaminh83** [comment]
Nah, not in my case. I'm running: 
```
$ lotus-miner version
Daemon:  1.14.4+calibnet+git.5b33555fd+api1.4.0
Local: lotus-miner version 1.14.4+calibnet+git.5b33555fd
```
And got those two sectors stuck in `FinalizeReplicaUpdate` and still getting slashed. 

So I have tried changing states and removing the sectors. And YES it does not say `ERROR: normal shutdown of state machine` anymore. But on the other hand - it did not do a thing to the sectors 👎

```
$ lotus-miner sectors update-state --really-do-it 3 Removing
$ lotus-miner sectors update-state --really-do-it 5 Removing 
$ lotus-miner sectors update-state --really-do-it 3 AbortUpgrade
$ lotus-miner sectors update-state --really-do-it 5 AbortUpgrade
```

And still: 
```
$ lotus-miner sectors list
ID  State                  OnChain  Active  Expiration                    Deals  DealWeight  
0   Proving                YES      YES     2223840 (in 1 year 21 weeks)  CC                 
1   Proving                YES      YES     2225996 (in 1 year 21 weeks)  1      2.703GiB    
2   Proving                YES      YES     2228336 (in 1 year 21 weeks)  1      2.7GiB      
3   FinalizeReplicaUpdate  YES      NO      2229509 (in 1 year 21 weeks)  1      5.426GiB    
  RecoveryTimeout: 821366 (in 3 weeks 5 days)
4   Proving                YES      YES     2250128 (in 1 year 22 weeks)  1      6.868GiB    
5   FinalizeReplicaUpdate  YES      NO      2268176 (in 1 year 23 weeks)  1      2.988GiB    
  RecoveryTimeout: 844406 (in 4 weeks 6 days)
6   Proving                YES      YES     2270398 (in 1 year 23 weeks)  CC
```

Or we can go: 
```
$ lotus-miner sectors terminate --really-do-it 3
$ lotus-miner sectors terminate --really-do-it 5
$ lotus-miner sectors terminate flush
ERROR: no sectors were queued for termination


```
So bottom line - I still have my sectors in `FinalizeReplicaUpdate` and can't get rid of them! 

lotus-miner logs is empty - no response on these commands at all.

**Comment by Reiers** [comment]
All my `FinalizeReplicaUpdate` reverted back to to a fail state or succeeded here.
Do you still have the files for those sectors, or did you manually deleted them? @benjaminh83

**Comment by Reiers** [comment]
`lotus-miner sectors update-state --really-do-it 5 AbortUpgrade`

-

`lotus-miner sectors abort-upgrade --really-do-it 5` is the correct way. _I know the Docs are wrong._ 

What happen if you entered:
`lotus-miner sectors remove --really-do-it 3`
-or 
`lotus-miner sectors expired --remove-expired`

Also if you have deleted the files, can you try making the files again - with touch (create ghost sector on the worker) restart miner + worker and see if it changes the state to failed?

**Comment by benjaminh83** [comment]
Yes, sector files was manually deleted to ensure passing WindowPoST. With partially files in the folders, it crashed the WindowPoST. 

lotus-miner is not responding to the suggested commands: 

```
$ lotus-miner sectors remove --really-do-it 3
$ lotus-miner sectors remove --really-do-it 5
$ lotus-miner sectors expired --remove-expired
Removing sectors:
Sector  State   Expiration

All 0 sectors listed above will be removed

To confirm removal of the above sectors, including
 all related sealed and unsealed data, run:

lotus-miner sectors expired --remove-expired --confirm-remove-count=0 --expired-epoch=743771

WARNING: This operation is irreversible
```

And still same state: 
```
$ lotus-miner sectors list
ID  State                  OnChain  Active  Expiration                    Deals  DealWeight  
0   Proving                YES      YES     2223840 (in 1 year 21 weeks)  CC                 
1   Proving                YES      YES     2225996 (in 1 year 21 weeks)  1      2.703GiB    
2   Proving                YES      YES     2228336 (in 1 year 21 weeks)  1      2.7GiB      
3   FinalizeReplicaUpdate  YES      NO      2229509 (in 1 year 21 weeks)  1      5.426GiB    
  RecoveryTimeout: 821366 (in 3 weeks 5 days)
4   Proving                YES      YES     2250128 (in 1 year 22 weeks)  1      6.868GiB    
5   FinalizeReplicaUpdate  YES      NO      2268176 (in 1 year 23 weeks)  1      2.988GiB    
  RecoveryTimeout: 844406 (in 4 weeks 6 days)
6   Proving                YES      YES     2270398 (in 1 year 23 weeks)  CC  
```   

But hey: 
```
$ lotus-miner sectors abort-upgrade --really-do-it 3
$ lotus-miner sectors abort-upgrade --really-do-it 5
```
And I got an entry in the miner logs: 
```
2022-03-04T14:37:36.008+0100    INFO    miner   miner/miner.go:479      completed mineOne       {"tookMilliseconds": 3, "forRound": 744676, "baseEpoch": 744675, "baseDeltaSeconds": 6, "nullRounds": 0, "lateStart": false, "beaconEpoch": 1699000, "lookbackEpochs": 900, "networkPowerAtLookback": "2528052110163968", "minerPowerAtLookback": "343597383680", "isEligible": true, "isWinner": false, "error": null}
2022-03-04T14:38:06.009+0100    INFO    miner   miner/miner.go:479      completed mineOne       {"tookMilliseconds": 4, "forRound": 744677, "baseEpoch": 744676, "baseDeltaSeconds": 6, "nullRounds": 0, "lateStart": false, "beaconEpoch": 1699001, "lookbackEpochs": 900, "networkPowerAtLookback": "2528052110163968", "minerPowerAtLookback": "343597383680", "isEligible": true, "isWinner": false, "error": null}
2022-03-04T14:38:36.384+0100    INFO    miner   miner/miner.go:479      completed mineOne       {"tookMilliseconds": 4, "forRound": 744678, "baseEpoch": 744677, "baseDeltaSeconds": 6, "nullRounds": 0, "lateStart": false, "beaconEpoch": 1699002, "lookbackEpochs": 900, "networkPowerAtLookback": "2528052110163968", "minerPowerAtLookback": "343597383680", "isEligible": true, "isWinner": false, "error": null}
2022-03-04T14:38:39.603+0100    INFO    sectors storage-sealing/input.go:530    aborting upgrade of sector      {"sector": "5", "trigger": "user"}
2022-03-04T14:38:41.809+0100    INFO    sectors storage-sealing/input.go:530    aborting upgrade of sector      {"sector": "3", "trigger": "user"}
2022-03-04T14:39:06.008+0100    INFO    miner   miner/miner.go:479      completed mineOne       {"tookMilliseconds": 4, "forRound": 744679, "baseEpoch": 744678, "baseDeltaSeconds": 6, "nullRounds": 0, "lateStart": false, "beaconEpoch": 1699003, "lookbackEpochs": 900, "networkPowerAtLookback": "2528052110163968", "minerPowerAtLookback": "343597383680", "isEligible": true, "isWinner": false, "error": null}
```

But still: 
```
$ lotus-miner sectors list
ID  State                  OnChain  Active  Expiration                    Deals  DealWeight  
0   Proving                YES      YES     2223840 (in 1 year 21 weeks)  CC                 
1   Proving                YES      YES     2225996 (in 1 year 21 weeks)  1      2.703GiB    
2   Proving                YES      YES     2228336 (in 1 year 21 weeks)  1      2.7GiB      
3   FinalizeReplicaUpdate  YES      NO      2229509 (in 1 year 21 weeks)  1      5.426GiB    
  RecoveryTimeout: 821366 (in 3 weeks 5 days)
4   Proving                YES      YES     2250128 (in 1 year 22 weeks)  1      6.868GiB    
5   FinalizeReplicaUpdate  YES      NO      2268176 (in 1 year 23 weeks)  1      2.988GiB    
  RecoveryTimeout: 844406 (in 4 weeks 6 days)
6   Proving                YES      YES     2270398 (in 1 year 23 weeks)  CC   
```

**Comment by benjaminh83** [comment]
Seems like @Reiers classic trick of creating fake sector files did the trick. 

Its now responding to termination requests, so lets see if this gets cleaned up now 👍 

```
$ lotus-miner sectors list
ID  State          OnChain  Active  Expiration                    Deals  DealWeight  
0   Proving        YES      YES     2223840 (in 1 year 21 weeks)  CC                 
1   Proving        YES      YES     2225996 (in 1 year 21 weeks)  1      2.703GiB    
2   Proving        YES      YES     2228336 (in 1 year 21 weeks)  1      2.7GiB      
3   TerminateWait  YES      NO      2229509 (in 1 year 21 weeks)  1      5.426GiB    
  RecoveryTimeout: 821366 (in 3 weeks 5 days)
4   Proving        YES      YES     2250128 (in 1 year 22 weeks)  1      6.868GiB    
5   Terminating    YES      NO      2268176 (in 1 year 23 weeks)  1      2.988GiB    
  RecoveryTimeout: 844406 (in 4 weeks 6 days)
6   Proving        YES      YES     2270398 (in 1 year 23 weeks)  CC 
```

**Comment by Reiers** [comment]
So after further testing - update-state,terminate, remove works and no longer ends with: `ERROR: normal shutdown of state machine`.

It does not revive old stuck sectors that missing the files(removed manually) - so you will need to:

```
create a dummy sector in your/storage/sector/path touch s-t0xxxxx-sectornumb
Restart the miner
See if that changes the state
lotus-miner sectors remove --really-do-it <sectorNR>
lotus-miner sectors terminate --really-do-it <sectorNR> again.
```
^ USE ONLY ON STUCK/Zombie SECTORS!

From now on, if you are on `v1.14.4` or later you should not run into this issue again.

I will open a new ticket if I see reports on new sectors that are stuck, but for now im closing the issue ticket since it solved the issue I describe above.
